### ISSUE TITLE
[Open-Meteo] Wrong timezone on current location

### ISSUE THREAD

**Issue by ildar** [breezy-weather/breezy-weather#1038]
### Steps to reproduce

1. Add a new widget to the homescreen that includes time/date
2. Choose the city manually: Нур-Султан
3. Time is one hour off from expected in both the preview and on the widget

### Expected behavior

Time should match my system time

### Actual behavior

Time is showing +one hour than expected.

### Weather source used

Open-Meteo

### Breezy Weather version

5.2.1_freenet

### Android version

Android 13 GSI

### Device

AGM H3

### Other details

having the same problem as https://github.com/breezy-weather/breezy-weather/issues/942 I couldn't write into that issue as it is closed (why this restriction???)

> Duplicate of https://github.com/breezy-weather/breezy-weather/issues/870?

No. This is different. The city chosen implicitly.

I'm in TZ Asia/Nur-Sultan.
I suspect Breezy Weather takes timezone from some different source, not from the system.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.2 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> having the same problem as https://github.com/breezy-weather/breezy-weather/issues/942 I couldn't write into that issue as it is closed (why this restriction???)

As you said yourself, the issue is closed, no one will reply to a necroposting. It's also a different issue than yours, since you can reproduce the issue in a version later than 5.2.0. It's also different because you add a city manually, while others add "current location" which works differently (reverse geocoding VS location search.

> Time should match my system time

That's not the expected behavior. Time will match the time in the location you chose.

> I'm in TZ Asia/Nur-Sultan.

Open-Meteo says it's Asia/Almaty.

https://geocoding-api.open-meteo.com/v1/search?name=%D0%9D%D1%83%D1%80-%D0%A1%D1%83%D0%BB%D1%82%D0%B0%D0%BD&count=10&language=ru&format=json

According to https://techcommunity.microsoft.com/t5/azure-integration-services-blog/timezone-changes-in-kazakhstan/ba-p/4108495?WT.mc_id=DT-MVP-5001664

It looks like your country changed the timezone of the country recently from UTC+6 to UTC+5, which is exactly the issue you have. Why didn't you mention it in your issue? It would have saved investigation time.

Please report the issue to https://github.com/open-meteo/geocoding-api/issues and request an update of the GeoNames database, explaining your country changed timezone recently and you need an updated database.

**Comment by papjul** [comment]
Nevermind, updating the GeoNames database would not change anything. The GeoNames database also has Asia/Almaty timezone: https://www.geonames.org/1538317/astana.html

If it is correct, you might want to update the TimeZone database of your device (don't ask me, I have no idea how to do that): https://source.android.com/docs/core/permissions/timezone-rules?hl=en#timezone-apex

If it is not, you might want to report the timezone change to GeoNames, then once it is updated, ask for an update on Open-Meteo side.

**Comment by ildar** [comment]
Greetings, Julien

> Time should match my system time
>
> That's not the expected behavior. Time will match the time in the location
> you chose.
>
This is the surprising behavior. The core of this issue.
I suggest fixing or at least having an option for this behavior.

Please report the issue to
> https://github.com/open-meteo/geocoding-api/issues and request an update
> of the GeoNames database, explaining your country changed timezone recently
> and you need an updated database.

thanks, I'll do that.
And thank you for your time dedicated to this wonderful app, best in class
imho.

**Comment by papjul** [comment]
> I suggest fixing or at least having an option for this behavior.

Sorry, no, it makes no sense to show Kazakhstan timezone when showing weather for New York (or any other city with a different timezone). It would show a sun when it's actually night.

**Comment by ildar** [comment]
Nur-sultan and Almaty have the same TZ per s.e. So it's ok that one points
to another.

**Comment by ildar** [comment]
So the true issue reason was:
1. The widget shows the time according the TZ of the target city obtained
from OS.
2. The OS has wrong TZ infos.

Yet
> Sorry, no, it makes no sense to show Kazakhstan timezone when showing
weather for New York (or any other city with a different timezone). It
would show a sun when it's actually night.

The widget doesn't show the location so looking at it doesn't give any clue
it's the other location's weather and the other location's time. I'd say
it's misleading.
