### ISSUE TITLE
Incorrect feels like temperatures for SMHI

### ISSUE THREAD

**Issue by hurried6158** [breezy-weather/breezy-weather#1052]
### Steps to reproduce

1. Go to the hourly forecast of city configured to use SMHI as a source.
2. Compare feels like in app with those found in SMHI webpage.

### Expected behavior

Display the correct feela like values in the hourly forecast pane.

### Actual behavior

Displaying incorrect feels like values.

### Weather source used

SMHI

### Breezy Weather version

5.2.3

### Android version

Android 14

### Device

Google Pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
It's not because there are different values on the website and on Breezy Weather that Breezy Weather is necessarily wrong. As you can guess, "feels like" is subjective and there are tens of method of calculation.

The value shown on the SMHI is not public, they don't give us this data, otherwise we would use it, so we fallback to a Wet Bulb computing approximation.

If you are interested in knowing how you will feel when going outside, I would rather have a look at the different individual values like wind (mostly winter), cloud cover and dew point (mostly summer), rather than "feels like".
