### ISSUE TITLE
Separate requestLocationSearch and requestReverseLocationSearch from WeatherService

### ISSUE THREAD

**Issue by kosmoz** [breezy-weather/breezy-weather#107]
### Describe your suggested feature

First of all: Hi! And thank you for continuing the legacy of this great application!

### Problem description

Currently, the app bundles weather and location related APIs in the same interface. The reason for this is probably, that the original weather providers (AccuWeather and China) offer both of these in a more or less tightly coupled way[^1]. The more recently added weather providers (all, except for the two above) unfortunately do not provide some or all of the location related APIs and this can lead to some issues:
1. The name of the current location is never updated.
2. If the provider is changed to something other than AccuWeather before the current location is acquired for the first time, it will never work.
3. Currently, the app uses Open-Meteo for location search when a different provider is selected that does not offer such an API itself. This is (in my opinion) not a big privacy issue, since Open-Meteo is generally pretty friendly in that regard, but it is sort of intransparent to the user.

### Proposed solution

For these reasons and since there is no intrinsic reason for location APIs and weather APIs to be in the same service, I propose that `requestLocationSearch` and `requestReverseLocationSearch` should be refactored to a separate interface (e.g. `LocationService`). This way, a service for a weather provider that provides some or all of those methods can still implement them. Additionally, there should be a settings item for selection a location search provider. This settings item can be visible or hidden depending on whether a given weather provider supports external location providers.

As a free and Open Source location search provider that offers APIs for both geocoding and reverse geocoding, I suggest [Photon](https://photon.komoot.io/), which I have used in the past and works quite well (not affiliated).

### Alternative solution

The solution proposed above requires quite a lot of changes. A simpler solution would be to use different API providers for `requestLocationSearch` and `requestReverseLocationSearch` in services for weather providers which do not offer these (this is already done for `requestLocationSearch`, but not for `requestReverseLocationSearch`), however I think this should be communicated to users more transparently. 

[^1]: As far as I understand, they both rely on a "city ID" to fetch weather data.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Yes, this will be done as part of #20 or #89, whichever comes first

**Comment by papjul** [comment]
>     2. If the provider is changed to something other than AccuWeather before the current location is acquired for the first time, it will never work.

Regarding this point, I noticed it while working on a33361a431c0cca673ac7e65234222ae11929d51 and fixed it. It was because I didn’t change the city Id which was still defined to “not found city”. Since we don’t need city ids, I just put lon and lat as city Id.

> As a free and Open Source location search provider that offers APIs for both geocoding and reverse geocoding, I suggest [Photon](https://photon.komoot.io/), which I have used in the past and works quite well (not affiliated).

Everything based on OpenStreetMap is not implementable. I initially implemented Nominatim to use with MET No, and since it didn’t have timezone, which is highly mandatory, I had to bundle a 30 Mo library that could calculate timezone from coordinates. Even with it, it took ~1 min to calculate, it was a terrible experience. OpenStreetMap has said multiple times they will never store timezones in their database.

The best option now is GeoNames, however this may get rate-limited, hence why I use Open-Meteo, which is based on the same data, but not as complete (postal codes, admin codes, reverse geocoding). Admin codes are useful for some providers to get alerts for a specific admin area (by admin code).

My analysis leads me to think that making GeoNames (or GeoNames-based) the default search/reverse geocoding provider is the best option.

If I go that way, I could implement area levels 1-5 from GeoNames and store them in `Location` in app database, which would help me having more consistency in locations (currently, we only store one administration level called `province`, however depending on providers, this admin area is not the same everywhere).

**Comment by papjul** [comment]
If you opened this issue because you intended to implement a new weather provider, I would still wait a bit, as I refactor even more so that you no longer have to call the `CommonConverter` to complete missing data (this would automatically be done later).
