### ISSUE TITLE
WMO alert got cut off mid sentence

### ISSUE THREAD

**Issue by KrisadaFantasy** [breezy-weather/breezy-weather#1184]
### Steps to reproduce

1. Choose **WMO Severe Weather Information Centre** as alert source
2. Receive alert

### Expected behavior

Receive alert in full, complete sentence.

### Actual behavior

Alert got cut off mid sentence.

### Weather source used

WMO Severe Weather Information Centre

### Breezy Weather version

5.2.5 from Izzy

### Android version

HyperOS 1.0.1.0 based on Android 13

### Device

Redmi Note 11S

### Other details

![0](https://github.com/breezy-weather/breezy-weather/assets/85682504/e816839b-abb9-468e-8259-da58d6611134)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.5 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Yes, it's because the implementation is not yet complete, and that's why we don't recommend it yet. Basically, WMO gives us a list of all alerts matching for your coordinates with a truncated description, so that's an expected behavior. To have the full description, we then need for each alert to load an URL with the original alert, which will contain additional info, such as full description, translations, consequences, etc. It's tracked as part of #808
