### ISSUE TITLE
Reflect forecasted data in notification in-between update intervals

### ISSUE THREAD

**Issue by jayb-g** [breezy-weather/breezy-weather#1269]
Currently the app updates the main screen and the forecast notification only when the background refresh interval is hit, which is by default 1.5 hours. While doing this app doesn't fully utilize the already fetched hourly forecast data to show live weather(even if its forecasted, and not really live) in-between the refresh interval.

Let's say forecast for today is 
9.00 - Partly cloudy
10.00 - Rain
11.00 - Overcast
12.00 - Overcast
13.00 - Thunderstorm - Heavy Rain

Now if the app had updated data at say 8.50, next update would be at 10.20. Till then it will keep showing Partly cloudy and not Rain after 10.00
Similarly, it will keep showing overcast until 13.20.

It should instead show the weather forecast closest to the current time. Maybe the app can have an internal refresh rate of 15 mins for that? 

Note: I understand there's a refresh rate setting for foreast update. But I'm not talking about that. Default of 1.5hours seems just fine. I'm suggesting an impvoement in how the already fetched forecast data can be better used, even with longer refresh intervals.

**Comment by papjul** [comment]
From my understanding, you would like to use observations data for current for -let’s say- 15 min, then after that period, fallback to hourly forecast to not use past observations.

At first sight, I see two difficulties:
- Hourly forecast is not that reliable. You can see that just by freshly refreshing and comparing your hourly forecast with the current observations. There is sometimes a huge gap because forecast and observations by stations don't work the same way at all. (For sources with no observations, such as Open-Meteo, however, it will be the same data)
- For some sources forecast for 9:00 can mean "forecast from 8:00 to 9:00", for others "forecast from 8:30 to 9:30" and for others "forecast from 9:00 to 10:00", so it's hard to know which one to pick in the situation you describe
- The refresh of notifications and widgets happen only when there is an actual refresh of weather data, this would mean adding an additional process -let’s say- every 15 min, which Android doesn't like much when there are too many works scheduled and with a frequent rate. There is a [high risk of being killed](https://dontkillmyapp.com/) on some devices such as Xiaomi, Samsung or others

If you would like to discuss it further, please fill in the Idea template: https://github.com/breezy-weather/breezy-weather/discussions/new?category=ideas

**Comment by papjul** [comment]
It is invalid because you didn't use the template. I don't even know how you were able to report an issue without using one.
