### ISSUE TITLE
[wallpaper] low FPS on Galaxy A13

### ISSUE THREAD

**Issue by TailsFanLOL** [breezy-weather/breezy-weather#1277]
### Steps to reproduce

1. Enable live wallpaper
...that's it.

### Expected behavior

It should run close to screen refresh rate.

### Actual behavior

It appears very laggy. I don't know how to measure it, but it is definitely below 24 and judging by the rain animation it is around 15. It only applies to the live wallpaper and runs very smoothly in app.

### Weather source used

OpenMeteo

### Breezy Weather version

5.2.7_freenet

### Android version

Android 14 armv7

### Device

Samsung Galaxy A13 (fuck my life)

### Other details

Nun

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.2.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
- Why don't use armv8?
- Can you try setting your screen refresh rate to 60 Hz instead of the default 90 Hz, and let us know if it helps?

> It only applies to the live wallpaper and runs very smoothly in app.

While it's the same wallpaper, technically it works VERY differently as you can read in #1006. I personally don't recommand using this feature at all, but users prefered a flawed implementation than no feature, that's why we didn't remove it.

**Comment by papjul** [comment]
Ah, I found something on Internet regarding a 90 Hz screen, but it wasn't a well-known source.

It runs smooth on my device, but the thing is that the battery issue and FPS issue are tied together because of how many things are done every second on the device.

Can you try setting wallpaper to Rain condition and Always day? Just so we see if avoiding the most consuming operations help.

**Comment by TailsFanLOL** [comment]
> Can you try setting wallpaper to Rain condition and Always day? Just so we see if avoiding the most consuming operations help.

Where is that set? It's not under view, widgets or debug.

**Comment by TailsFanLOL** [comment]
Nvm, found it. Yes, it is laggy when I set it to rain.

**Comment by papjul** [comment]
Did you also define "Always day" (or "Always night") instead of automatic?

**Comment by TailsFanLOL** [comment]
No, but I tried it and it doesn't appear to make a difference if it's night or day

**Comment by papjul** [comment]
I just tried on a Galaxy S2, a very old device from 2011, and I can ensure you the rain live wallpaper is completely smooth on this device, despite having much much lower specs.

Please make sure you use an updated stock ROM, otherwise I have no idea.

**Comment by TailsFanLOL** [comment]
I don't have an idea either, but for some reason it's this way

**Comment by papjul** [comment]
Is there something we can do on our side for this issue?

It works fine on a device with much lower specs, so I can only suggest checking regularly for new One UI updates…
