### ISSUE TITLE
Adjust color scheme of location search to match color scheme of location list

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#139]
### Describe your suggested feature

Currently, the location list and the location search are among the first screens a user sees after a clean install of the app. However, the color scheme used in both screens varies which is especially noticeable when using a Material You color scheme with bright colors. Thus, I'd suggest adjusting the color scheme used in the location search to match the one used in the location list / rest of the app.

This affects the following two areas in the location search:

1. background: use the background color that is used in the location list and settings
2. FAB: use the primary color from Material You / default color used in location list (for the non-Material You version)

<details><summary>screenshots for comparison</summary>

### Material You light theme
| location list | location search | 
| --- | --- |
| ![Material You location list](https://github.com/breezy-weather/breezy-weather/assets/97251923/fd03b704-f9b3-4e80-a266-f0bfb79a5cc6) | ![Material You location search](https://github.com/breezy-weather/breezy-weather/assets/97251923/b69e19b4-cd6b-4b1b-b6ba-63c9c4768113) |
| background color is identical to the one used in settings | background color seems to be derived from the Material You color scheme</br></br>lower section has a different background color |
| FAB color used is primary color from Material You | FAB color used is secondary or tertiary color from Material You |

### Material You dark theme
| location list | location search | 
| --- | --- |
| ![Material You dark design location list](https://github.com/breezy-weather/breezy-weather/assets/97251923/c57fa148-493f-4ccd-a900-2f8f8e493d8e) | ![Material You dark design location search](https://github.com/breezy-weather/breezy-weather/assets/97251923/d1bff5ea-6ba1-4a6b-9893-a0389c291a7e) |
| see remarks for Material You light theme | see remarks for Material You light theme |

### Non-Material You
| location list | location search | 
| --- | --- |
| ![LG G6 location list](https://github.com/breezy-weather/breezy-weather/assets/97251923/0b50be8a-1da3-456f-bf20-506daf74f652) | ![LG G6 location search](https://github.com/breezy-weather/breezy-weather/assets/97251923/f1c3e6cc-3627-4a7f-9c61-b8c8f7690e00) |
| see remarks for Material You light theme | see remarks for Material You light theme |

</details>

### Other details

Normally, I don't use the dark theme, but when creating this issue I briefly enabled it to get screenshots for the location screens. Apart from the abovementioned remarks I noticed some UI elements like the top app bar (back arrow, search icon) and certain texts (location names) where it feels strange that they use the primary color from Material You. But that's a topic for a separate issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Background for search activity is intended, as it is in the guideliens for Material 3, although I have a slightly different implementation due to the nature of the search in Breezy Weather.

![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/459a3062-4d16-4ab1-b3e5-aeed117cff94)

I will have a look at other points.

**Comment by min7-i** [comment]
As far as I can see, the only thing that is still open here, is the color of the FAB in the bottom app bar, right?

It's been a while since I created this issue and I'm not sure if we should still change that. What's your opinion, @papjul?

**Comment by papjul** [comment]
You can make a pull request for the FAB button.

Otherwise, I don't think more important changes are needed. There are plans to replace that search page with a new page like Google Maps:
- A search bar at the top
- A map with `osmdroid` lib
- You can pinpoint to put a specific neighborhood instead of a city.
- Searching for a city with the search put all results on the map on a [bottom sheet](https://m3.material.io/components/bottom-sheets) were all results are listed and you can just tap an "Add" button

It's a lot of work and I'm focused on quick fixes and better charts for a long time, and we lack a reverse geocoding for the manual pinpoint feature, although we could still implement the rest and leave that for later. Let me know if that's something you would want to work on? I could help along the way.

**Comment by min7-i** [comment]
> You can make a pull request for the FAB button.

Alright. I'll do that.

> Let me know if that's something you would want to work on? I could help along the way.

I'll think about it and will let you know.

**Comment by papjul** [comment]
Follow-up in  #10
