### ISSUE TITLE
National Weather Service

### ISSUE THREAD

**Issue by chloyster** [breezy-weather/breezy-weather#146]
### Describe your suggested feature

Add support for the NWS API at https://api.weather.gov/

### Other details

I have looked into adding this API myself. I started getting a skeleton going on a local branch based off the new provider guide that was made. Idk how much time I have to work on it, but I think it would be good to have regardless. So figured Id make the feature in case anyone else was interested

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Correct me if I'm wrong but looking at endpoints, it seems to me you only have temperature, wind speed and alerts available.

You can implement it, but you will lack so many data, so I'm not sure it will be very useful.

**Comment by chloegix** [comment]
https://www.weather.gov/documentation/services-web-api#/default/gridpoint_forecast

https://api.weather.gov/gridpoints/TOP/31,80/forecast

https://www.weather.gov/documentation/services-web-api#/default/station_observation_latest

https://api.weather.gov/stations/KSBP/observations/latest

Above are documentation and examples of a couple calls. This gives a good amount of data. Idk if it's everything though. I've only just started looking at the documentation.

Ive had other apps which use the nws as the source. Unless they are pulling data from the other sources in the background I think they should have a good selection. Iirc, basically every US based weather provider gets their data from NWS first

**Comment by papjul** [comment]
No, no, that’s fine, just wanted to warn you to not have your expectations too high, given it seems very basic ;)

**Comment by HonestAbe7** [comment]
I am very excited that you guys are trying to get the NWS forecasts too. I just think AccuWeather is so inaccurate. Looking forward to the upcoming changes.

**Comment by papjul** [comment]
> I am very excited that you guys are trying to get the NWS forecasts too. I just think AccuWeather is so inaccurate. Looking forward to the upcoming changes.

If you are in the US, AccuWeather has better accuracy than NWS almost all the time.
Check your city here: https://www.forecastadvisor.com/

**Comment by HonestAbe7** [comment]
Thanks for the link.

Well, all I can say is that AccuWeather here in my U.S. city says the air quality is poor and NWS says good. Looking outside and breathing the air, I would say it is good. Plus, in my city, the temperature is ALWAYS above what it is really outside for AccuWeather. So I will stick with the NWS. Right now, I use Today Weather app (for NWS) and this app for AccuWeather for the severe alerts. Hoping I could switch to this app only in the future.

**Comment by chloegix** [comment]
I also use Today Weather for the NWS provider. I'd love to look at what they do because they provide way more data points than I see available in the API :)

**Comment by papjul** [comment]
> Looking outside and breathing the air, I would say it is good.

That’s not how air quality works. For example, carbon monoxide is colorless, odorless, tasteless, and non irritant, people die every year in their house without even noticing they were poisoned.

Additionally, you can’t compare AccuWeather index and NWS index as they don’t use the same scale. Both AccuWeather and Breezy Weather uses the Plume Labs index which is based on WHO thresholds, which are way lower than American standards. For example, there is no safe level of PM2.5/PM10, so even when we say < 5 ug/m3 is good, it’s wrong, but WHO decided of a threshold as low as possible.

So, even if you implemented NWS air quality in Breezy Weather, Breezy Weather would calculate index as per the Plume Labs scale, so you would have more or less the same result.


> Plus, in my city, the temperature is ALWAYS above what it is really outside for AccuWeather.

Air temperature is officially measured in the shade at a height of about 6 feet, above ground, which may explain difference in temperature felt and measured temperature, especially if you measure outside temperature by yourself without these precautions. But AccuWeather and NWS measure the temperature the same way, so there should not be difference on this matter.

Btw, latest version of Breezy Weather fix a long-time bug which may have caused issues with Fahrenheit unit (it was converted from Celsius, but since it was rounded twice, once in Celsius and once in Fahrenheit, this could have lead to big differences, now it is rounded to 1 decimals).

**Comment by papjul** [comment]
For the past week, I spent a lot of time abstracting a lot of logic from weather provider, so now it should be easier than ever to implement a new provider, even with basic programming skills.

I couldn’t find your fork, so I guess you didn't start yet, but in case you did, please rebase your changes on latest main. Contribution guide was also updated, there are now much less things to do.

If there are missing info from the Contribution guide, feel free to give me your feedback so that I can add it for future other contributors!

(In case you no longer want to implement the API by yourself, let me know and I will tag this issue as "Open to contributions")

**Comment by chloegix** [comment]
Oh, good to know! Yeah I never pushed my branch, as I havent had a ton of time to look at it. Ill rebase though and check out what was added.

Thanks!

**Comment by chloyster** [comment]
@papjul you can go ahead and tag this as open to contributors. I still would ideally like to work on it, but have been much busier than expected. I don't want to be why it's held up anymore and anyone else who wants to give it a crack can go ahead

**Comment by papjul** [comment]
I started working on it but API is based on a grid of 2,5 km x 2,5 km, which is not based on lon/lat, and each office in US has its own office, so we need to save the gridId, gridX and gridY. Additionally, for alerts, we need to save the county identifier. Currently, database only allows to save an unique identifier for a city, but not many parameters like that, so it's a bit tricky, but not impossible; it requires to add a new transversal way of saving location preferences/data per location/source first.

**Comment by papjul** [comment]
Will be in next version. Remains to do: alerts as a secondary source
