### ISSUE TITLE
Add humidity/dew point graph

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#15]
### Describe your suggested feature

Add humidity/dew point graph

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by Zahrun** [comment]
+1 for Humidity graph

**Comment by christasich** [comment]
Also, interested in dew point/humidity for both daily and hourly graphs! I'm especially interested in dew point since it's a much better indicator of how muggy it actually feels. It's really useful for warm, humid climates as compared to relative humidity which feels vastly different depending on the temperature.

**Comment by papjul** [comment]
I'm not sure what kind of information a daily humidity chart should hold and for what use case? I'm working on better hourly charts in #252, wouldn't it be enough?

**Comment by christasich** [comment]
@papjul I find it more useful to see charts of dew point at the daily level. Where I live (Southeast US), we have long stretches of warm, humid weather (30-40C) and the daily dew point can vary greatly (10-24C). For example, a 32C day with a 24C dew point earlier in the week will feel much more humid and significantly hotter than a 35C day with a 14C dew point later in the week. It's nice to be able to graphically see when this drop in humidity occurs. This also changes on an hourly scale when a weather front passes through so it's still nice to see it at the hourly timescale like #252, but I find it less important for my use case.

**Comment by papjul** [comment]
So the important data for you is average (not median?) humidity from all 24 hours of a day? Or by half day (day and night)? I'm not sure we can have this kind of data from a lot of sources (I know we have it in Open-Meteo). Currently, we don't store this data at daily level, while the hourly humidity is already stored, ready to be displayed in UI.

> It's nice to be able to graphically see when this drop in humidity occurs.

I understand better now, because as it can vary greatly during the day, I was thinking it would not be helpful as an average will not reflect a humid morning and a dry afternoon, for example.

**Comment by christasich** [comment]
> So the important data for you is average (not median?) humidity from all 24 hours of a day? Or by half day (day and night)?

Yes. The daily average would capture this the best. Even having the daily max and min would be useful. But, since the data isn't readily available, a viable alternative may be #252 but with the ability to show >24 hours. This would be similar to the way it appears in Weawow Weather which is another app that I've used. As long as I can see how the dew point is changing somewhere in the app, I would be happy. :)

**Comment by Zahrun** [comment]
I am currently living in a tropical area, and I learned that the humidity level is as important as the temperature to determine the day’s weather. It is easy to measure humidity percentage, but the actual feeling of the humidity percentage depends on the temperature. Both have to be considered together. That is why dew point is considered a better measure. I am curious to see a graph of how the due point evolves during the day.
The humidity factor is also included in the "real feel" or "feels like" value, which I have seen here sometimes be 10°C more than the actual temperature due to high humidity level. So personally, I would be happy with a graph of the "feels like" value which is even easier to interpret than dew point in my opinion.

**Comment by papjul** [comment]
> The humidity factor is also included in the "real feel" or "feels like" value

Not necessarily, it depends on the source. For example, sources using the wind chill temperature will only take wind in the formula. There are actually tons of "feels like" formulas, so it's not consistant, and they don't really mean anything (it has nothing to do with a temperature unit).

Meanwhile, the dew point has a unique formula that actually mean something (the temperature at which there is 100% humidity), so it's really good to understand how dry/humid it is (which is the point of the new chart discussed here).

**Comment by papjul** [comment]
Implemented in 2155d085abf72f2e86a031ad1099f96bf29d7704

**Comment by Zahrun** [comment]
Awesome, thanks! <3
