### ISSUE TITLE
Daily Widget with Oreo style is too long on Wednesdays at 100% text size

### ISSUE THREAD

**Issue by Syberkonda** [breezy-weather/breezy-weather#1563]
### Steps to reproduce

Place daily widget on home screen. Use the settings below. 

![Screenshot_20241227-193820_1](https://github.com/user-attachments/assets/84e106f5-f900-43d1-a666-226adba97d51)

Expand the widget on your launcher so that the widget has as much horizontal space as possible when the device is in portrait mode. 

### Expected behavior

No matter the day of the week, no text should move to a second line. This is how it was for me up until a few months ago. 

### Actual behavior

Even when I expand the widget to be as large as possible, the text runs onto a second line in Lawnchair (Figure 1) and the GrapheneOS stock launcher (Figure 2).

Figure 1. 
![Screenshot_20241225-192630_1](https://github.com/user-attachments/assets/2ce37fd2-1047-4c9e-9078-8ae4860e90cc)

Figure 2. 
![Screenshot_20241225-192308_1](https://github.com/user-attachments/assets/aa9b3a44-3fab-460f-a1b4-9334eaec37a7)

I do not remember which version this issue cropped up in. 

### Weather source used

AccuWeather

### Breezy Weather version

5.3.1

### Android version

GrapheneOS 15 (AP4A.241205.013)

### Device

Pixel 6 Pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
- [X] I checked that my issue is not covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document.
- [X] I have updated the app to **[version 5.3.1 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)** and I can reproduce the issue in this version.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language. I can write in my native language under the English text, if necessary.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Just reduce the text size setting?

I mean there are so many devices widths, accessibility settings, different languages for the date, etc, that it's not unusual to sometimes fits on one line, and sometimes not, so you have to adjust accordingly. And I disagree it should stay on a single line if it doesn't fit. I prefer it on two lines -albeit not very pleasant- rather than keeping it on a single line and having the line cropped at the end and missing the unit (or worse, the temperature value). Wdyt?

**Comment by Syberkonda** [comment]
I see what you're saying, but I am bringing this up because it wasn't an issue before. Also, the Pixel 6 Pro is 1440p on the short side. This is not a not-standard width. I understand your argument about the language, but to be frank, it would not be unreasonable to expect for something like this to fit at the default size in English. Yes the text width can be changed, but the 10% jumps in text size rather large and, again, we're talking about a default setting here. IMHO, it's not unreasonable to expect for something like this to "just work" at a standard width, and I think it would make sense to either give us the ability to more finely tune text size (e.g. 1% jumps) and/or change the actual font size of the 100% setting. 

I hope I'm not sounding too harsh, and I just want to thank you for all you do with this project. I have yet to find another weather app that surpasses Breezy Weather.

**Comment by papjul** [comment]
> change the actual font size of the 100% setting

It's not reasonable due to all the differences of languages, devices (different widths), accessibility settings. If I change the text size for your device/language, why shouldn't I do it for all different kind of devices, languages, system font and grandma phones in the world? Then the text size will just be tiny, just to be sure it doesn't go on two lines on some devices.

> I think it would make sense to either give us the ability to more finely tune text size (e.g. 1% jumps)

That would be an idea request, rather than a bug. However, I won't suggest to open one, since legacy widgets are no longer maintained and the text size configuration will no longer be available in future widgets.

The future widgets from #937 won't be affected by this issue as they will not feature a configurable text size, and will adjust to the available space instead.

For the legacy widgets, the suggested workaround is the text size configuration ;)
