### ISSUE TITLE
[AccuWeather] Duplicate alerts with only minor changes in content instead of replacing old alerts

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#159]
### Steps to reproduce

Users complain of duplicate alerts but it’s AccuWeather which is sending same alerts with different unique IDs while it should be the same. Not much we can do on our side if even AccuWeather is not able to deduplicate them, but tracking the issue here in case some people are looking for this issue.

### Expected behavior

I should receive only one orange alert for thunderstorm from 16:00 to 18:00 instead of two with only minor changes in text.

### Actual behavior

I receive two alerts.

### Weather provider used

AccuWeather

### Breezy Weather version

Non relevant

### Android version

Non relevant

### Device

Non relevant

### Other details

A previous bug #73 was fixed in v4.2.0 to fix another case of duplicate alerts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by yonoff** [comment]
It would be nice if there was an option to hide alerts in the app settings.

**Comment by min7-i** [comment]
Are you talking about alert notifications? If so, there is already a setting to disable notifications for weather alerts in the notifications category in settings.

In case you're talking about the alerts shown on the main screen in the app and a way to disable them, I suggest that you **[open a new idea ](https://github.com/breezy-weather/breezy-weather/issues/new?assignees=&labels=Idea&projects=&template=new-idea.yml)** for that because it's a different topic than the one discussed here in this issue.

**Comment by papjul** [comment]
Do you still have duplicate issues with AccuWeather?

A few versions ago, we switched to alerts by coordinates, instead of by city, which avoids having alerts for all districts of the city.

I will put this issue as “Needs more info”; it will be closed if no one still have issues (or if it only happens in non-significant cases).
