### ISSUE TITLE
Rewrite China provider to use API search instead of hardcoded list of cities

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#173]
### Describe your suggested feature

As title says.

This will allow to:
- Get rid of a huge chunk of specific-code related to Chinese cities
- Allow searching Chinese cities with their English names

Feasibility must be studied, there may be some reasons why it was not done that way in Geometric Weather.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by losky2987** [comment]
This is because the API provided by Chinese weather service providers does not include city name query, you can only query by city code or latitude and longitude, and many weather service providers charge for a large number of queries.
I found the weather query API web page provided by Baidu, you can use the translation function of the browser to read it： https://lbsyun.baidu.com/faq/api?title=webapi/weather/base
At present, retaining specific-code related to Chinese cities is the only option.

**Comment by papjul** [comment]
Provider for the weather data has a search API and it gave me results when I searched for "Beijing" (written in English), so I'm not worried about that.
