### ISSUE TITLE
Can't decrease the vertical size of Widget.

### ISSUE THREAD

**Issue by nit511** [breezy-weather/breezy-weather#177]
### Steps to reproduce

Add a 'Material You - Current' widget to homescreen.

### Expected behavior

Expected widget size - 2x2

![Screenshot_20230717-031837_Lawnchair](https://github.com/breezy-weather/breezy-weather/assets/103308339/1aa90e7b-df7b-4cb3-8a82-ca2a44bcbe06)
(this one is google's widget)

### Actual behavior

Actual widget size - 2x3

![Screenshot_20230717-031408_Lawnchair](https://github.com/breezy-weather/breezy-weather/assets/103308339/3e218feb-8f6e-481f-88ee-f983ef6582b3)
(this one is breezy weather's widget)

### Weather provider used

AccuWeather

### Breezy Weather version

4.2.1-beta

### Android version

Android 13

### Device

Poco x4 pro 5g

### Other details

I can't downsize the 'Material You - Current' widget vertically.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by srbsolihull** [comment]
I have the same issue in the Pixel Launcher. Works as expected in Nova.

**Comment by min7-i** [comment]
Just to clarify, the issue is that the widget is taking up 2x3 space while the actual size is 2x2, correct? (If so, it's been reported for Geometric Weather as well, WangDaYeeeeee/GeometricWeather#400)

To add some context here are two screen recordings (Android stock launcher & nova launcher), both with a home screen raster 5x5.

<details><summary>screen recordings</summary>

https://github.com/breezy-weather/breezy-weather/assets/97251923/dc0685f2-3990-4f8d-9556-d5e589ee26b2

https://github.com/breezy-weather/breezy-weather/assets/97251923/e4f616a2-ad2f-4854-a818-4b9ad9a069be

</details>

**Comment by nit511** [comment]
Yes its correct, i want 2x2 widget size like google's widget but this one is not decreasing than 3 grids vertically.
I uses Pixel Launcher.

If its already mentioned in 'WangDaYeeeeee#400', then should i delete this issue from here? I don't know about this.

**Comment by min7-i** [comment]
> If its already mentioned in 'https://github.com/WangDaYeeeeee/GeometricWeather/issues/400', then should i delete this issue from here? I don't know about this.

No, please leave it open. My comment was only meant as a remark that this issue already exists in Geometric Weather and isn't a bug that was caused by changes in Breezy Weather.
