### ISSUE TITLE
Background refresh happening when offline

### ISSUE THREAD

**Issue by balporig** [breezy-weather/breezy-weather#211]
### Steps to reproduce

1. Go offline (airplane mode / no wifi or mobile data)

### Expected behavior

No background jobs should be started when offline. The app should detect and run jobs only when there is internet connection

### Actual behavior

Background refresh is still triggered when offline on the configured refresh interval. If you're offline for an extended period of time, each new job gets stuck, and I've noticed extensive battery drain

Continuation to #172 

### Weather source used

AccuWeather

### Breezy Weather version

v4.3.0-beta

### Android version

Android 10 & 13

### Device

Samsung Galaxy S9/ Faifphone 4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I turned on airplane mode when going to bed last night. Last sync was before I went to bed.
I turned off airplane mode when waking up and the background update resumed after that.
Notification history confirms that no background updates happened during the night.

We ask Android to only do the job when network is connected.
See here: https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/java/org/breezyweather/background/weather/WeatherUpdateJob.kt#L407

More info needed:
- Are you using a non-standard Android (custom ROM, MIUI, etc)?
- When you turn on airplane mode, do you still have some network on (VPN, wifi, mobile, etc)?

**Comment by Spark4000** [comment]
I wish I could get the app to refresh in the background. Geometric Weather 2.608-foss works flawlessly

**Comment by min7-i** [comment]
Please have a look at the FAQ about [background updates](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md#background-updates) and try the steps suggested there, if you haven't done that already.

In case that doesn't help, feel free to ask for help in the [Github discussions](https://github.com/breezy-weather/breezy-weather/discussions/new?category=q-a) or in the [Matrix help channel](https://matrix.to/#/#breezy-weather-help:matrix.org).

By the way, this issue here is about a different aspect of background updates, so if you want to discuss your question further, please refer to the channels I mentioned above.

**Comment by papjul** [comment]
> I wish I could get the app to refresh in the background. Geometric Weather 2.608-foss works flawlessly

This is a different issue, please [read FAQ](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md), you will find solution for background updates not working.

**Comment by papjul** [comment]
> Okay, when the huge battery drain was observed (around 20%) I had several of the Breezy notifications for the periodic refresh and assumed is caused by jobs related to them.

Didn't you report the background update issue happening for the 2 devices? Wasn't it initially a bug report about background updates happening while offline on BOTH devices?

We tell Android system to launch the background update every X hours (depends on your config) only when network is up, then it's not up to Breezy Weather to launch it, it's Android that will take care of that. If, let's say, Samsung which is well known to have non-standard Android behaviors, decides it's a good idea to launch multiple jobs at the same time, there is nothing we can do. You can have a look at the Don't kill my app! website, maybe it can help having a more standard behavior regarding background jobs: https://dontkillmyapp.com/samsung

> You say that ”job gets stuck”, but even in the job itself we immediately throw an error if network is not available -> Are those errors in the logs?

Yes, but it can only happen if you have network when background update is launched and you quickly turn on airplane mode after that, otherwise it won't be launched (at least, that's what we tell Android to do).

> let's keep this issue open for now if it appears again

OK, but not indefinitely, I will add the "stale" tag so that it gets closed in a week without update, so that we don't keep not reproduceable issues forever. Make sure you are running v4.4.0+ on both devices before you do any more tests ;)
