### ISSUE TITLE
"ignore when battery is low" - background refresh still happens when opening app

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#215]
### Steps to reproduce

1. Activate "ignore when battery is low" setting.
2. Choose the lowest refresh interval, normally 30min.
3. Make sure you have at least one working location in your location list.
4. Exit the app.
5. Wait for one refresh interval, in this example 30min.
6. Reopen the app.

### Expected behavior

No background refresh is done.

### Actual behavior

A background refresh is performed.

https://github.com/breezy-weather/breezy-weather/assets/97251923/3853c3d1-6923-4e42-b3f4-9c55c8612900

### Weather source used

not relevant

### Breezy Weather version

4.3.0-beta

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

Affects all versions since 4.2.0-beta.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Help](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) documentation.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Few possibilities I see:
- When you tap "Ignore when battery is low", there is a one time request to update that is triggered after new constraints were applied. Maybe you didn’t go back to home screen after you switched the preference right after that.
- “Ignore if battery is low” only applies to background updates. If you open the app, a “force refresh” will be done on main screen if it was not updated during the interval set for the background updates. What makes me think that is that your main screen shows “0 min ago”, so it seems it was just refreshed as you opened the app.
- Your battery is not low. I see that you are at 96% with battery-saving mode enabled, but the constraint is “ignore battery low”, not “ignore if battery-saving mode enabled”

Best to do for now is to enable notification history and check if you continue to see background updates being done regularly after you switched the preference.

If there are, then we will need to dig into the source code of the "batteryNotLow" constraint: https://developer.android.com/reference/androidx/work/Constraints.Builder#setRequiresBatteryNotLow(kotlin.Boolean)
Because as I said, I’m really not sure that we can consider “96% battery with battery-saving mode enabled” to be the same as “batteryNotLow”.
As far as I'm concerned, I'm just telling Android to not launch the job if battery is low, then it’s up to Android to decide if it wants to run the job.

**Comment by min7-i** [comment]
Thanks for looking into it.

I made the recording with 96% and battery saver enabled, but I tested the issue with different levels of battery (also below 30%). So I'd say that this isn't the cause of this issue.

The refresh is done when opening the app. I always considered this to be related to the background refresh, which is why I described it as a background refresh being performed. However, from your second bullet point I take it that there's a difference between the background refreshes and the force refresh when opening the app.

If the force refresh upon opening the app is intended even when the "ignore battery low" setting is active, then it works as expected and my issue is resolved.

**Comment by papjul** [comment]
> I made the recording with 96% and battery saver enabled, but I tested the issue with different levels of battery (also below 30%). So I'd say that this isn't the cause of this issue.

My device enters battery-saving mode at 15%, so I believe it’s the low battery level (I use LineageOS, I believe it’s rather close to AOSP behavior).


> If the force refresh upon opening the app is intended even when the "ignore battery low" setting is active, then it works as expected and my issue is resolved.

Yes, the “ignore battery low” is only for background updates as this is a constraint I put on the job (see my previous link). It should probably be documented somewhere, I concede.

If you have low battery and decide to open the app anyway, then I don’t find it odd to consider that the user wants to be presented with fresh data. It remains battery-efficient as only happens when you open the app (for example, you have a 30 min refresh rate with low battery at T = 0, and you open the app at T = 1 h 28, that saved you two background refreshes).

**Comment by min7-i** [comment]
> My device enters battery-saving mode at 15%, so I believe it’s the low battery level (I use LineageOS, I believe it’s rather close to AOSP behavior).

Mine is set to do this at 30%, but from what I could tell as long as the battery saver is active the background refresh will not be performed when "ignore when battery is low" is enabled as well - at least on my Pixel with GrapheneOS. I think that's quite handy when you want to save some battery by manually enabling the battery saver.

> Yes, the “ignore battery low” is only for background updates as this is a constraint I put on the job (see my previous link). It should probably be documented somewhere, I concede.

For me, I'd say it was the snackbar "Updated in background" that appears after the force refresh which led me to believe it's a background update. Maybe changing that to a text which doesn't include "background", e.g. "Updated automatically", would be more fitting.

> If you have low battery and decide to open the app anyway, then I don’t find it odd to consider that the user wants to be presented with fresh data.

That's a valid point. Then the setting currently does work as it's suppose to.

**Comment by papjul** [comment]
> For me, I'd say it was the snackbar "Updated in background" that appears after the force refresh which led me to believe it's a background update. Maybe changing that to a text which doesn't include "background", e.g. "Updated automatically", would be more fitting.

I agree with you, but I must be honest and tell you that I have no idea how come this message shows up. It’s only supposed to be happening after the background update job completes, but we don’t launch any background job from the main screen, except on app update. This spaghetti code will be reworked when working on #198, however I don’t want to dig into that for now, I want a bit of stability after everything that happened so far. However, once done, this should fix this issue as well as #204.

I would suggest closing this issue and adding a comment on #198 regarding this “Updated in background” message, I don’t feel like it needs a dedicated issue (as it will only be worked on as part of #198).

**Comment by min7-i** [comment]
That sounds like a good idea. I'll add a comment to #198.
