### ISSUE TITLE
Use empty space above the temperature on app's home screen with animations turned off

### ISSUE THREAD

**Issue by m1chj** [breezy-weather/breezy-weather#238]
### Describe your idea

There's quite a lot of empty space which could be displaying data instead. How it is:

![n](https://github.com/breezy-weather/breezy-weather/assets/45080190/6eff4391-38c4-4c04-ac8e-ce8e80cd1187)

How I think it's better:

![y](https://github.com/breezy-weather/breezy-weather/assets/45080190/b903d863-775b-4482-81c5-249e4f03a44e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
I already about half-reduced this empty space from Geometric Weather. Some people preferred the old way, while some wants no space at all. Sometimes I have to find a "fits most" implementation.
Letting the text breathe is important in design.
Regarding animations off, some elements will be added back such as clouds, see #195.
I notice that you don’t have a 16:9 screen. Currently, empty space is calculated as a % of height, which makes the empty space more important on your device than on mine. I will keep this issue open to switch to a fixed size, which will reduce the height of this empty space for your device.

**Comment by m1chj** [comment]
@papjul you added more empty space instead of reducing it, this is Geometric Weather's home screen with animations turned off

![3](https://github.com/breezy-weather/breezy-weather/assets/45080190/977d570a-29df-4fc0-a555-aa9d30a79c51)

**Comment by papjul** [comment]
> @papjul you added more empty space instead of reducing it, this is Geometric Weather's home screen with animations turned off

Please compare comparable things! Geometric Weather doesn’t have option to turn animations off, I know that because I'm the one who implemented it. Instead, you’re showing me an old *less* animated background type that was removed years ago, long before I forked this project.

Geometric Weather has a very clear implementation, the first card starts at 66% of the window height. My implementation makes header details start at 30% of window height, so that’s roughly half of what Geometric Weather did.
