### ISSUE TITLE
Make "Saved locations" more intuitive to find by changing icon or improving semantic

### ISSUE THREAD

**Issue by Rexadev** [breezy-weather/breezy-weather#244]
### Describe your idea

Title

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
You can add more than one location by using the search feature

**Comment by Rexadev** [comment]
> (icon on top right of location list)

where is that

**Comment by papjul** [comment]
<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/574669ce-f5cd-4f17-a097-07cea2e9ba71" width="300" />

**Comment by Rexadev** [comment]
@papjul where is locations panel ?

**Comment by loucasal** [comment]
You can access it by tapping the 'bookmark' icon on the main screen.
@papjul, I must say I understand the confusion: I was also quite surprised by the choice of icon at first. Perhaps a globe would be more intuitive?

**Comment by papjul** [comment]
Bookmarks represent things you save, such as saved locations.
This is what Google uses for Google Maps. for example.
I agree this may not be ideal, but at least this is an icon that is universally understood as "saved things" ; a globe would be too generic, it could mean many things. Geometric Weather previously used a building, even more unintuitive.
Some other apps use a [list icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:list:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=list&icon.platform=android), but it feels too generic to me, especially where the icon is located, this could be misunderstood as "reorder items".

**Comment by loucasal** [comment]
How about a pin? That should be a more understandable symbol for location, definitely more than the bookmark.

**Comment by papjul** [comment]
I don’t think so, pin is to pin something at the top of a list, or something like that. Never saw that icon used in another context.

**Comment by papjul** [comment]
The new example you added after editing looks better, however the home inside refers to the home location, but we save all kind of location in the location list. And the location icon without home inside is the icon used when locating someone (location services), so I would like to avoid using this one for other purposes as some people have a location list without using any location services. I tried to look at other variants of the location icon but couldn’t find a fitting one.

**Comment by Rexadev** [comment]
![image](https://github.com/breezy-weather/breezy-weather/assets/62152714/bf446d1c-bb6d-46d9-bb8b-a4b1b2381761)
![image](https://github.com/breezy-weather/breezy-weather/assets/62152714/ea1a319e-4429-4831-a203-cd87a362617f)
![image](https://github.com/breezy-weather/breezy-weather/assets/62152714/29af7a39-e756-42c0-b0f7-6a4c67435f30)
![image](https://github.com/breezy-weather/breezy-weather/assets/62152714/bfccecc9-f202-402e-bce3-e79164fb7697)
![image](https://github.com/breezy-weather/breezy-weather/assets/62152714/146aef21-f65e-43e7-a618-51c8fa7f99c3)

@papjul @loucasal

**Comment by papjul** [comment]
Please only suggest Material icons, we can’t use these icons.

> ![image](https://user-images.githubusercontent.com/62152714/256998056-bf446d1c-bb6d-46d9-bb8b-a4b1b2381761.png)

This is the icon for current location, most users who would see this would think of "current location", not "access to my saved locations".

> ![image](https://user-images.githubusercontent.com/62152714/256998064-ea1a319e-4429-4831-a203-cd87a362617f.png)

This is the icon for navigation, most users who would see this would think of "Google Maps navigation", not "access to my saved locations".

> ![image](https://user-images.githubusercontent.com/62152714/256998085-29af7a39-e756-42c0-b0f7-6a4c67435f30.png)

Explained in my previous messages, this is the icon we use for location services, I would prefer not re-using the same icon for two different purposes. Android also uses this icon for location services, so users are used to this usage of the icon.

> ![image](https://user-images.githubusercontent.com/62152714/256998094-bfccecc9-f202-402e-bce3-e79164fb7697.png)

The same one with multiple places icons on the globe would fit, not just one. However, since the icon is small, we can’t put that many details on it, so it won’t be possible.

> ![image](https://user-images.githubusercontent.com/62152714/256998120-146aef21-f65e-43e7-a618-51c8fa7f99c3.png)

This is the icon for "search on the Web", not an icon for accessing a list of saved locations.

See why I said "it may not be an ideal icon, but it’s the best we can find”, because there is no widely known alternative (and if there is, I just want to be proved wrong), all icons you showed serves other purposes that will only add confusion.

______

I suggest we go back to a higher level to understand the issue.

1) The first time you install the app, you access the location list and you have a short explanation on how to add locations, so after adding your first location, you know this menu exists and has the purposes of handling multiple locations, right?

So when you tell yourself "how do I access back the location list":
2) You see two icons on top right: bookmarks and gear icons, why didn't it feel intuitive to you that this is the bookmarks icon of the two available ones?
3) When trying to access back the location list, did you think it was the gear icon and did you tap on it?
4) If you did, why when you didn't find your locations on the gear icon, didn't you try to tap on the bookmarks icon after that? (It’s not like there are many icons to try)

No judgment, I just want to understand the process, at what moment there is a sticking point so I can find ways to improve it.

**Comment by loucasal** [comment]
Yes, most users will eventually figure it out. In some cases by trial and error. In my case, partly thanks to the muscle memory of where the building icon was in Geometric Weather. But I do remember thinking "let's see where this icon takes me, I can't tell from the context".

I will try to explain why I find it semantically unclear:
- During the process of adding a location, the user is never asked to "save" anything. They just look up and select a _location_ (and possibly edit the weather source). So the concept they will think of is indeed location (globe, pin, building, etc.).
- Even the screen itself the icon leads to is called "Locations", not "Saved locations" (and even if it was, the noun would be more memorable than the adjective).

(Also, Google Maps uses both an icon and a text label for clarity, but that's beyond the point.)

**Comment by papjul** [comment]
> Yes, most users will eventually figure it out. In some cases by trial and error. In my case, partly thanks to the muscle memory of where the building icon was in Geometric Weather.

That’s interesting, so you had no problems with the `domain` icon? I did the change from `domain` icon to `bookmark` on purpose because an user had reported it was not fitting, and I agreed with them.


> I will try to explain why I find it semantically unclear:
> 
>     * During the process of adding a location, the user is never asked to "save" anything. They just look up and select a _location_ (and possibly edit the weather source). So the concept they will think of is indeed location (globe, pin, building, etc.).
> 
>     * Even the screen itself the icon leads to is called "Locations", not "Saved locations" (and even if it was, the noun would be more memorable than the adjective).

Understood, thank you for taking time  to pinpoint what is probably the issue. I understand the semantic issue, and as a non-native English speaker, I’m currently in the process of asking a native English speaker review the whole translation. I will let them know to have a particular attention on this point.


> (Also, Google Maps uses both an icon and a text label for clarity, but that's beyond the point.)

It is not beyond the point, our icon also has a label. The only difference is it’s a content description in our case (just long press on an icon when you are unsure of what an icon without label does).

<img src="https://github.com/breezy-weather/breezy-weather/assets/1449159/14aaa4ad-ca50-49aa-80f3-174ba36804f1" width="300" alt="Screenshot" />

**Comment by Rexadev** [comment]
https://fonts.google.com/icons?query=rock&icon.query=location&icon.style=Rounded

@papjul @loucasal

**Comment by NBA613** [comment]
How about [Edit Location](https://fonts.google.com/icons?query=rock&icon.query=edit+location)?
I understand it's not "Location List", however, the user's intent is to change the location displayed, and is therefore brought to the locations page. The user can then change to a saved location, or search for a new one.

Alternatively, use a list icon but place it near the location name, implying "Location List".

Most ideal for location list would be [this](https://www.onlinewebfonts.com/icon/130092) or [this](https://www.onlinewebfonts.com/icon/292479), however, they are not Material.

**Comment by papjul** [comment]
> How about [Edit Location](https://fonts.google.com/icons?query=rock&icon.query=edit+location)?

Unfortunately, there *is* an Edit location in the same page in the footer to specifically edit the location currently seen, and it would be confusing to have both and one of them being the location list.

> Most ideal for location list would be [this](https://www.onlinewebfonts.com/icon/130092) or [this](https://www.onlinewebfonts.com/icon/292479), however, they are not Material.

Thank you, I like them, I will check if I can reproduce something similar, maybe combining `places` with `list` (3 items).

**Comment by papjul** [comment]
What about "Explore" as in "Explore other places":
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/7b33ff84-9163-4e61-a0ae-445c40a50768)

Or a custom icon based on multiple "place" icons, such as something like that (roughly done):
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/6a057058-1fba-4015-b334-602f41b915af)

**Comment by Rexadev** [comment]
Why not Earth

**Comment by papjul** [comment]
At this point, I don’t know what to say, you find the bookmarks icon unintuitive (which is fine), but every time you suggest something, it’s even more unintuitive.

For example, I don’t know what a first-time user would think when seeing an Earth icon, but personally I would think of "Open on the web"/"Open in a webview", when seeing this:
![image](https://github.com/breezy-weather/breezy-weather/assets/1449159/2acce0af-5ec0-485a-84cf-f59d2096ed7c)

Additionally, when I ask you questions or suggest icons, you ignore me and just post new icons, so without your inputs, I can’t find the best way to improve the user experience.

**Comment by Rexadev** [comment]
Earth says Location, Place

**Comment by loucasal** [comment]
> What about "Explore" as in "Explore other places": ![image](https://user-images.githubusercontent.com/1449159/257041354-7b33ff84-9163-4e61-a0ae-445c40a50768.png)
> 
> Or a custom icon based on multiple "place" icons, such as something like that (roughly done): ![image](https://user-images.githubusercontent.com/1449159/257041552-6a057058-1fba-4015-b334-602f41b915af.png)

Both would be an improvement, but if I have to choose one, I would go for the latter - it maps much more closely to the action / screen the user is taken to. We would just need to make sure it is graphically clear.

Thanks again for all the impressive work on this app, by the way!

**Comment by papjul** [comment]
> Earth says Location, Place 'Geo'graphic

I know what an Earth can convey but you continue ignoring all my other points.
I’m starting more and more to think that the initial issue is an attention deficit (initially, you asked to implement a feature, even though you saw that feature the first time you opened the app!). Nothing wrong with that, but unfortunately, this is not something I can fix.

I don’t know a lot of open source developers that would have spent so much on one single icon, I think I did my share on this issue.
So to prevent us wasting more of our time, I’m locking the thread and will think of something later.

(thanks @loucasal for your inputs, I appreciate!)
