### ISSUE TITLE
Enable the function of automatically refreshing weather.

### ISSUE THREAD

**Issue by amokiel** [breezy-weather/breezy-weather#248]
### Describe your idea

I used to open the weather app every time, but each time I need to drop down to refresh the current weather. So I'm asking for a function that enables automatic refresh of the weather app. 
That way, I think it'll be easier. If possible, I beg for this function and hope it can be implemented. 
Sorry to interrupt. Thank you very much for your efforts. This app looks good and works well. I hope it will be better. 
Thank you very much, the developer worked hard!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Breezy Weather should honor the "refresh rate" setting from Settings > Background updates.
If for any reason the background update failed, it will refresh if weather was updated more than "refresh rate time" ago.

If it does not, please show a screenshot of your refresh rate setting + a screenshot of your first location from your location list that was not refreshed (you will need to switch app before, if you keep screen on for 2 hours straight, it will probably do nothing).

Closely related issues:
- If you have any background update issues, please [check FAQ](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md)
- There is also an ongoing issue closely related, #204 that you saw pinned

**Comment by papjul** [comment]
In that case, I’m sorry but it won’t be possible because:
- if a user keeps opening and closing the app, it will refresh all the time, maybe even before the previous refresh is done!
- models are refreshed at best once an hour. Although there might be some little exceptions for some particular data, it’s mostly useless to refresh at intervals less than 30 minutes. Additionally, some providers send header instructions to not contact server again before X (datetime) so you would be served the same cached data.
- we ask for fair usage of API and resources. This app and these API are provided for free and shared by all users of Breezy Weather. If we notice abuse, we will deny the ability to force refresh before at least 15 min are elapsed

**Comment by papjul** [comment]
> Thank you for your patience. I thought it was easy. My sincere apologies for taking so much of your time.

No worries! I feel it’s important to have transparency in the process of decision, even if it takes me a few additional time to explain ;)
And maybe other users will have the same idea as you and will be happy to find this issue and the reasons why it’s not implemented ;)
