### ISSUE TITLE
Improve Refresh rate settings dialogue

### ISSUE THREAD

**Issue by Cod3dDOT** [breezy-weather/breezy-weather#255]
### Describe your idea

Idea 1: Replace selector with a slider that snaps to 30min / 1h / 2h / 3h / 6h / 12h / 24h
Idea 2: Use freed-up space to show amount of calls per day

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Idea 1:
A slider only works with fixed intervals (if it was 1 hour by 1 hour between each, it would be OK). Even if you somehow was able to have not regular intervals, you would still have to keep it proportional, so for example the 12-hour would be in the middle and 24-hour at the end of the slider, then all others would have to fit in the remaining left space.

Idea 2:
If I understand correctly you want the (24/interval in hours) info? I don't think that's a good idea because:
- Android does not guarantee it will run every X hours (additionally we have a 10-min backoff policy)
- It will not run if offline (it will be postponed until there is network, for example you turn off your phone at night and it resumes in the morning)
- It will not run if battery low if you enabled the setting
- Some custom ROM have an impredictable behavior regarding scheduled workers

So I think we can't show a reliable info, and it may lead to users reporting issues if the info shown does not match reality.

If instead you are interested by history (runs in the next previous 24 hours, you can use the notification history from Android).

**Comment by Cod3dDOT** [comment]
Those are good points. Closing as the idea will not improve the app.
