### ISSUE TITLE
Allow to display Beaufort wind scale instead of wind speed

### ISSUE THREAD

**Issue by xuangeyouneihan** [breezy-weather/breezy-weather#303]
### Describe your idea

Well, I think m/s is not so intuitive, so the wind speed in the header and the widget should be changed to Beaufort wind scale.

![IMG_20230806_180226](https://github.com/breezy-weather/breezy-weather/assets/50788434/deed90e5-4651-4fe3-8336-70f2caa8c64c)

![IMG_20230806_180308](https://github.com/breezy-weather/breezy-weather/assets/50788434/039758e6-aecf-41d1-8a64-b0b82f727e5e)

Adding Beaufort wind scale to speed units might be also a good choice.

![Screenshot_2023-08-06-18-05-03-441_org breezyweather](https://github.com/breezy-weather/breezy-weather/assets/50788434/dab6be20-bbc4-452f-9425-34aedbf253ad)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [x] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
Beaufort wind scale is not an unit, it's a scale/index.
For example:

| Speed in km/h | Beaufort wind scale |
| ---- | --- |
| 62 | 8 |
| 74 | 8 |
| 75 | 9 |

If we were to convert between units according to a formula, 74 would be 8.9 or something like that. However, since it’s an index, it’s always 8 between 62 and 74 km/h.

However, as it is regularly requested, I will see what I can do to allow you to see an index instead of an unit.
