### ISSUE TITLE
Move the description of the weather source to a settings page (instead of the bottom).

### ISSUE THREAD

**Issue by ayntk-ai** [breezy-weather/breezy-weather#308]
### Describe your idea

Move the display of the weather sources to a separate menu instead of the boot menu, it would look much cleaner. And just show the names of the weather sources on the bottom. Intead of this text that is cut of or expanded just looks crazy:
![Screenshot_20230806-124953_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/122374094/ba329357-2fb2-4965-bfdf-464fef5e1c5d)
![Screenshot_20230806-124957_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/122374094/3a513d8d-b7b2-420e-9ec0-fb7a934734c8)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
You already know what I'm going to say…

1) It is mandatory to display credits for the data NEXT to where it is used, to be allowed to use it. Some sources such as AccuWeather also requires we put their logo as well, so I will also add that in future versions.

2) It has nothing to do in settings as it depends on sources selected for each location.

3) I made multiple efforts to not make it annoying:

- Air quality by Open-Meteo
- Pollen by Open-Meteo

becomes:

- Air quality & Pollen by Open-Meteo

So that the long text for Open-Meteo is not displayed twice.

4) And finally the text shows max 3 lines by default, so this seems obvious, but just don't expand it if you don't like it expanded?

**Comment by ayntk-ai** [comment]
I had not considered that. Thank you for your time and your prompt and complete reply.
