### ISSUE TITLE
Location-based Provider Selection Feature

### ISSUE THREAD

**Issue by maninthemiddle01** [breezy-weather/breezy-weather#312]
### Describe your idea

I find that my location list gets crowded when I use different weather providers for the same location to compare. I was wondering if it would be more manageable to implement a drop down menu for location based provider selection.

This feature would allow users to easily choose from the multiple available weather data sources, ensuring they receive the most accurate and reliable weather information for their specific location.

Here's a brief outline of the proposed location-based provider selection feature:

1. Accessibility: Include a clearly visible and accessible drop-down menu within the location view, allowing users to select their preferred weather data provider easily.
2. Location-based suggestions: Integrate the app's location tracking functionality to automatically suggest the most relevant providers based on the user's current location.
3. Customization: Allow users to save their preferred provider settings, ensuring that the app remembers and uses their chosen source each time it is opened.
4. Tooltip assistance: Display a tooltip or short description for each provider, explaining their methodology, coverage, and any notable advantages or disadvantages.

I hope this could be beneficial for the overview of the application. Take this as a suggestion, as I do not know exactly how to make it clearer.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> I find that my location list gets crowded when I use different weather providers for the same location to compare.

Please don't do this, we are limited in API calls we can have for free for each source, so we ask for fair usage of API, or if every one do like you, all limits will be exceeded and no one will be able to use any source. I'm really worried about your usage if you say you're crowded!

Except China, all sources support worldwide so there is no such thing as "best source for location". When you live in France, you probably want to use Météo-France, but even in that case, most sources re-use the models from Météo-France behind the scenes anyway. So we cannot make recommandations based on location. Even these recommandations could change as sources tweak their data all the time.

My suggestions:
- If you live in US, you can use [Forecast Advisor](https://forecastadvisor.com/) (not all of our sources supported)
- When you select source, there is a "Help me choose" button, tap on it to access a very detailed document of differences between sources in Breezy Weather.

Anyway, I appreciate the time you took to fill in the issue form, but this is really not a direction I want to take the app into.

For example, putting a dropdown in the location list, this will make this feature always visible to everyone, while most people just set it once and forget (or at least, it's how I intend the app to be used). If you want to change the source, you can still do it from Edit button on each location footer since v4.5.1.

If you want to compare models before deciding which source you want to use, you can use a dedicated service such as [Windy.com](https://www.windy.com/), it will be much better than a mobile app. Or if you like comparing models at all time, use [Windy.com](https://www.windy.com/) all the time, they will always do it much better than I could ever be able to.
