### ISSUE TITLE
Precipitation Notification

### ISSUE THREAD

**Issue by nrestell** [breezy-weather/breezy-weather#336]
### Describe your idea

For sources that provide a minutely forecast, it would be great to have a notification that precipitation (rain/snow) was on its way. 
Thresholds would be required to reduce potential spam notifications based on %probability and/or intensity(mm/hr), e.g., only notify if intensity is ≥0.5mm/hour and probability is ≥50% - "Rain is expected in 32 minutes". These parameters could be made customizable. If it is already raining and app updates, notification should state how much longer rain is expected for, e.g., "Rain expected to last for at least X minutes."

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
We don’t have what kind of precipitation it is in the short-term precipitation forecast, so maybe we should use "Precipitation" instead of "Rain".

I think we can also give more info about the intensity this way:
- "Light precipitation" (≤ 2.5 mm/h)
- "Moderate precipitation" (≤ 7.6 mm/h)
- "Heavy precipitation" (≤ 50 mm/h)
- "Violent precipitation" (> 50 mm/h)

It will take maximum value on the short-term period, not average.

**Comment by papjul** [comment]
I opted for a simple implementation at first, no mention of light/heavy precipitation. Will be available in v4.6.15
