### ISSUE TITLE
Appearance: customizable corner radiuses

### ISSUE THREAD

**Issue by mpeter50** [breezy-weather/breezy-weather#340]
### Describe your idea

I think it would be a great addition if corner radius-es could be customized in the appearance settings. Additionally, if margin sizes could also be affected (categorically or with a global divider), that would be awesome!

The reason for this is that even though it is the trend, there is a considerable amount of people on the internet who are not fond of very-round corners and large empty spaces, and I am like that too. Usually I avoid apps like that, but with yours, the pros outweigh this, even though I still dont like that part of the design.

### Other details

I have recently found your app, and even though I liked GeometricWeather too, your additions are fantastic! :) Thank you for making this app. The first few versions (at least compared to when I found this fork) were crashing on my old device, but 4.5 is running well so far.

Also, something more relevant: in the past a I have thrown together a patch with changes like this for a few apps.
I don't know if I would have the time to find the way to make the changes, and also I don't have experience in Kotlin, but I think it might also be helpful if you would give some pointers in how would you start. I believe I could make more settings items on the appropriate settings page, but for example I can imagine that I would have problems setting the view properties, or finding where are they accessible.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
> I think it would be a great addition if corner radius-es could be customized in the appearance settings.

> there is a considerable amount of people on the internet who are not fond of very-round corners

Honestly, this is the first time I hear about them (I actually read the opposite, not having corners was something to avoid from an UX point) and I'm not sure to understand, we basically try to follow Material 3 guidelines so the app integrates well with the rest of the system.

If there is anything wrongly implemented with the current radius corners, it will be fixed, not become an option.

Here are the 7 existing shapes in Material 3 and where they are used:
<img width="502" alt="7 shapes of Material 3" src="https://github.com/breezy-weather/breezy-weather/assets/1449159/ce7f8c0b-a693-4534-8299-f0d4ced573f3">

> Additionally, if margin sizes could also be affected (categorically or with a global divider)

If you are talking about whitespace, the design needs to breathe. You can have a look at #14 if the issue is to be able to see more info on hourly trends.

> in the past a I have thrown together a patch with changes like this for a few apps.

Could you link to some of them? Maybe it will help me understand some things. Kotlin is very close to Java, so don't worry.

**Comment by mpeter50** [comment]
> Honestly, this is the first time I hear about them (I actually read the opposite, not having corners was something to avoid from an UX point) and I'm not sure to understand, we basically try to follow Material 3 guidelines so the app integrates well with the rest of the system.

It depends on who you ask. I believe there are people who like this, but I think that Material 2 and 3 have nothing in common with Material, which I actually liked. To me that is the simplistic, and 3 is just bloated.

Last time I have seen this opinion in this post about thunderbird's new look: https://lemmy.ml/post/2656907
I also remember that I had seen similar discussions on other forums too, but I don't really remember where exactly they were.

> Could you link to some of them? Maybe it will help me understand some things. Kotlin is very close to Java, so don't worry.

I haven't uploaded it to Github, it is very crude and mixed in with other changes too. Technically it is just an Xposed module that replaces the `rx` and `ry` parameters in every call to [android.graphics.Canvas](https://developer.android.com/reference/android/graphics/Canvas).drawRoundRect() with a value that I can set in a controller app. I have settled on 2 dp.
It's not perfect as this way it sets this radius to everything for the target app, but it could be fine tuned.

**Comment by papjul** [comment]
> Last time I have seen this opinion in this post about thunderbird's new look: https://lemmy.ml/post/2656907

From what I can see in comments, a lot of people are actually having the opposite opinion.

> > Could you link to some of them? Maybe it will help me understand some things. Kotlin is very close to Java, so don't worry.
> 
> I haven't uploaded it to Github, it is very crude and mixed in with other changes too. Technically it is just an Xposed module that replaces the `rx` and `ry` parameters in every call to [android.graphics.Canvas](https://developer.android.com/reference/android/graphics/Canvas).drawRoundRect() with a value that I can set in a controller app. I have settled on 2 dp. It's not perfect as this way it sets this radius to everything for the target app, but it could be fine tuned.

I thought you meant you pushed a patch as a pull request to existing projects as a contribution to Android apps. What you are suggesting can not fit the project.

> I think that Material 2 and 3 have nothing in common with Material, which I actually liked. To me that is the simplistic, and 3 is just bloated.

We only support Material 3 (with still some Material 2 code to migrate), and we follow its guidelines, we can’t implement preferences that would tweak the design to not follow its guidelines.

If you want a different design, the only way I would allow to do it in this project is to modularize to have the presentation part moved away from the logic code. From my understanding, that’s what [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi) is doing. Basically, there are forks that are leveraging all the power from the app with their own UI. Since it’s Kotlin, there are also desktop apps (which could be an excellent addition to the project!). However, as you can guess, it’s not a trivial task, and even I, am not confident in my skills to implement it. Even if I did, I have so many other things to do for this project, that it would be on the bottom of my priority list.
