### ISSUE TITLE
LGPLv3-or-later not compatible with LGPLv3-only

### ISSUE THREAD

**Issue by comradekingu** [breezy-weather/breezy-weather#382]
### Steps to reproduce

Translations were taken as LGPLv3-or-later and can not be relicensed to -only without negotiating this restriction with individual contributors.

### Expected behavior

Should be LGPLv3-or-later

### Actual behavior

Got changed to LGPLv3-only

### Weather source used

N/A

### Breezy Weather version

All

### Android version

N/A

### Device

N/A

### Other details

Can be changed in
https://hosted.weblate.org/settings/breezy-weather/breezy-weather-android/
https://hosted.weblate.org/settings/breezy-weather/glossary/

Also, adding a CoC on the project without asking contributors is not a nice thing to do
to people that contribute to libre software for no compensation precisely to help prevent authoritarianism.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.5.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance)

**Comment by papjul** [comment]
We weren't allowed to use LGPLv3 or later because we forked Geometric Weather that is LGPL 3.0 only. It was more of a mistake set up than relicensing, but if we just look at the change itself, I can understand it can be seen as an arbitrary change.

Which language did you translate? I will remove your changes.

**Comment by tuxayo** [comment]
> Translations were taken as LGPLv3-or-later and can not be relicensed to -only without negotiating this restriction with individual contributors.

Really? That's weird, wouldn't that be a problem only for the opposite? Like from LGPLv3 to LGPLv3+

It really seems this change is legal[1]: https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility
"I want to license my code under: LGPLv2.1 only" with "I want to copy code under: LGPLv2.1 or later" => OK
Same with GPLv2 only can copy code from GPLv2 or later.
The table doesn't show LGPLv3only but it would be very very surprising it wouldn't work the same as the two above cases.


[1] Sure it's possible to express disagreement

**Comment by tuxayo** [comment]
> Also, adding a CoC on the project without asking contributors 

What do you mean, it's been here since two months, isn't that pretty much the beginning of the fork?
https://github.com/breezy-weather/breezy-weather/blob/main/CODE_OF_CONDUCT.md
Were there several major contributors at the time? Even now is there even one person coming remotely close to papjul in terms of contribution effort? (even someone who doesn't code but would spend a lot of time answering in the issue tracker for example would count and other types of contributions as well)

> is not a nice thing to do

It's not nice to have by default some basic stuff written against harassment?
It's a long version of "don't be dick" with more explicitly details about what that means. Since many type of abuse and discriminations in pretty much all cultures are not really considered bad (even if officially illegal). And it's with the explicit responsibility put on the project maintainer(s) to actually do something and not just close their eyes in case of harassment or discrimination)

> not a nice thing to do to people that contribute to libre software for no compensation precisely to help prevent authoritarianism.

I wish more of the people contributing to libre software would do it for strong political reasons. Sure it's a fair share. But open source philosophy seems to be dominating. Just look at the share of projects with non-copyleft licenses or that are on GitHub or the use of non-libre editors.

But wait, "precisely to help prevent authoritarianism" ? What authoritarianism are you talking about? Having anti harassement and discrimination rules is to prevent horizontal abuse. It's a form of unfair authority that someone unilaterally takes over someone when abusing them. Without any rules, sure there is less potential for vertical hierarchical abuse. But at the expense of more potential for horizontal abuse. Actually even about the hierarchical abuse, having some rules written allows to have legitimacy to denounce eventual abusive behavior from the main contributors. Of course there is a conflict of interest for the enforcement. But if it's not a single person projet, that can have leverage on the others. And in any case there is some implicit hierarchy resulting from involvement differences. So without some written rules there is still some kind of hierarchy. And more potential for horizontal abuse.

Shall this be another ticket? This is massively out of topic.

**Comment by papjul** [comment]
I would prefer this debate to happen elsewhere, let's stick to the two points (I would have prefered two issues but let's go):
1) License: as @tuxayo pointed out, there doesn't seem to be any legal issue (actually, it fixes one!). If you want your contributions to be removed because you don't agree, please let me know, I have no problem removing them.
2) CoC: as @tuxayo pointed out, it's there since almost the beginning of the fork, probably even before Weblate was set up. Having it or not having it doesn't change a iota how the project is managed. You can have it and not enforce it, or not have it and still have a management similar to what is described in it. And yes, it basically just contains basic stuff about being nice to each other (which seems almost mandatory and shouldn't need to be said when we are working on a common project!). So I don't understand what is the problem.
