### ISSUE TITLE
Make pressure consistent between sources

### ISSUE THREAD

**Issue by mosiser** [breezy-weather/breezy-weather#429]
### Steps to reproduce

1. Open app
2. Change source to Open-Meteo

### Expected behavior

Displaying relative (sea level) pressure

### Actual behavior

Displaying absolute (surface) pressure

### Weather source used

Open-Meteo

### Breezy Weather version

4.6.4-beta

### Android version

android 11

### Device

Redmi N10s

### Other details

Other sources correctly show relative pressure.
Only Open-Meteo shows the wrong one.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.4 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
There have never been a clear guideline as to what the app expects from sources for pressure.

I didn't check all sources and what kind of pressure is available, but on Open-Meteo, I had the choice and I defaulted to actual pressure, because in app, it is written "atmospheric pressure", so I would expect the real pressure here, not a pressure adjusted as if it was at sea level.

I can understand adjusting to sea-level has some advantages, such as being able to compare easily the meaning of this value for any location, and especially if there are many variations of altitude in a specific city. However, if we do that, we need to add "at sea level" in the name, because it would be confusing IMO to just call it "pressure" and it not being the actual pressure where the location is.

I don't use that data a lot, so if you have any pro and cons between the two pressure indicators to share, I would gladly hear them.

It would also be interesting to know what other weather apps usually do, how they display it, etc.

**Comment by mosiser** [comment]
I don't think it would be very confusing... It's a weather app, and everybody uses relative pressure, when talking about forecasts...

As you said, the main advantage is to have the same values for everyone, to compare despite having different altitudes in the same locations, especially in mountain regions.
Absolute pressure has no utility, as far as I know. 

I have (like many other) a weather station, that shows abs. pressure and a "calculated" rel. pressure, and the surface pressure of OpenMeteo is useless (meteorologically) because it can't be compared, unless it is adjusted to the sea-level and then compared to the rel.pressure.

I agree with you that the main problem is the inconsistency between sources, but it's the case that only OpenMeteo displays a different value.

> because in app, it is written "atmospheric pressure", so I would expect the real pressure here, not a pressure adjusted as if it was at sea level.

I think both, abs and rel, are considered "atmospheric pressure".
Both are values indicating the pressure of the atmosphere.
They use only different scales.

You can think like that.
Location is based on coordinates. Latitude and longitude indicate not a 3D point, but a column.
The "atmospheric pressure" of a set of coordinates (eg Venice), may refer to surface pressure (0 mt), at the tip of the bell tower (100mt), or on a plane flying (500, 1000, 3000mt...).
All of these are "atmospheric pressure" of that 2D location; for simplicity and conformity, we use relative pressure, at sea level.
The other ones could be calculated from this one. 

But, for weather purposes, we only need a value that tell us if we are in an high- or low-pressure area, regardless of the altitude we are.
> It would also be interesting to know what other weather apps usually do, how they display it, etc.

The other sources (AccuWeather, MET Norway, OpenWeather,...) all uses relative pressure as default. Even on their websites.
I also have installed various apps, in the past, such as Forecastie, QuickWeather, Weather (BeoCode), OpenWeather, and other local ones: each one of these displays relative (sea level) pressure.

**Comment by papjul** [comment]
Good points.

> I have (like many other) a weather station, that shows abs. pressure and a "calculated" rel. pressure, and the surface pressure of OpenMeteo is useless (meteorologically) because it can't be compared, unless it is adjusted to the sea-level and then compared to the rel.pressure.

About that point, some phones seem to have an internal barometer now (I don’t know if we will support that some day, I would need to have such device).

But, if I'm in this case, I would probably be interested by pressure at the altitude I currently am, so I can compare it, no?

**Comment by mosiser** [comment]
> About that point, some phones seem to have an internal barometer now (I don’t know if we will support that some day, I would need to have such device).
> 
> But, if I'm in this case, I would probably be interested by pressure at the altitude I currently am, so I can compare it, no?

Yes, maybe.
But I think that, in this case, it is more likely that the barometer app will show you both absolute (registered from the sensor) and sea-level (calculated from absolute and altitude from GPS).

The main problem comparing surface pressures, is that they change quickly, from place to place.
If I remember correctly, it change approximately 1hPa every 8m of altitude.
So, if you want to compare them, you have to choose a very precise location on the map (at the same altitude), hoping that the DEM model they are using to calculate absolute pressure is enough precise.

In summary:
Comparing absolute pressures means that the sea-level pressure has to be adjusted for every point on the map, and you have to choose one precise point. And if you move, you have to change that point on the map.

Comparing sea-level pressure, instead, means that the relative pressure is the same for a large area, and it doesn't matter where you are in this area, you have to only adjust your personal absolute pressure to the relative one. Much easier.


In addition, with relative pressure you know that 1013hPa is the medium level, and every value above means high-pressure, every value below means low-pressure. Everywhere you are.
With absolute pressure? You have, in that location, 964hPa. Is it high or low? Tomorrow, you move to a place a little higher, and the pressure become 924hPa. Is it decreased, or increased? Sun or rain?


At the end, a weather app can shows both the values, so every use is satisfied. Or let the user choose.
But, if only one value is shown, it should be the sea-level one...

**Comment by papjul** [comment]
Yes, yes, don't worry, I agree with your points.

I was just showing one case where pressure taking into account altitude would be good, but it's quite possible indeed the barometer would have a feature helping estimate pressure at sea level (estimate because there are different parameters than just altitude).

I will review all sources to make sure they all use sea level.

In the future, it would also be good to add some UI elements to show that 1013.25 hPa is a "normal" pressure and add some indication when it's trending high or low. Along with next 24 hours line charts that I'm thinking about ;)
