### ISSUE TITLE
Network location providers

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#49]
### Describe your suggested feature

AMap and Baidu SDK network location providers will soon be removed as I can't maintain them.

We need to find an alternative for China users or users without Google Play Services. It seems there is a UnifiedNLP project that could fit, and includes the AMap and Baidu SDK providers.

TODO: investigate what is this UnifiedNLP project and if it can be used without microG. Add a documentation about it so that user can use it with Breezy Weather.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by TheGamer1002** [comment]
*"...UnifiedNlp alone does not provide any features, but acts as a middleware for multiple backends..."*
from their [repo](https://github.com/microg/UnifiedNlp):
List of backends for geolocation:

    [AppleWifiNlpBackend](https://github.com/microg/AppleWifiNlpBackend) - Uses Apple's service to resolve Wi-Fi locations. It has excellent coverage but the database is proprietary.
    [OpenWlanMapNlpBackend](https://github.com/microg/OpenWlanMapNlpBackend) - Uses OpenWlanMap.org to resolve user location but the NLP backend did not reach release-quality, yet. Users interested in a freely licensed and downloadable database for offline use should stick with openBmap for now - Last updated in 2015
    [OpenBmapNlpBackend](https://github.com/wish7code/org.openbmap.unifiedNlpProvider) - Uses [openBmap](https://radiocells.org/) to resolve user location. Community-created, freely licensed database that can optionally be downloaded for offline operation. The coverage [varies from country to country](https://radiocells.org/stats/countries) (it's best in central Europe).
    [MozillaNlpBackend](https://github.com/microg/IchnaeaNlpBackend) - Uses the Mozilla Location Service to resolve user location. The coverage is OK. Only the cell tower database is free.
    [LocalWifiNlpBackend](https://github.com/n76/wifi_backend) - Local location provider for Wi-Fi APs using on-phone generated database.
    [LocalGSMLocationProvider](https://github.com/rtreffer/LocalGSMLocationProvider) - Local opencellid based location provider backend. Has been surpassed by LocalGSMBackend which also has an OpenCellID option - Last update in 2014
    [LocalGSMBackend](https://gitlab.com/deveee/Local-GSM-Backend) - Local location provider for GSM cells. It works offline by downloading freely licensed database files from Mozilla, OpenCellID, or lacells.db.

List of backends for (reverse) geocoding:

    [NominatimGeocoderBackend](https://github.com/microg/NominatimGeocoderService) - Address lookup backend.

**Comment by papjul** [comment]
> _"...UnifiedNlp alone does not provide any features, but acts as a middleware for multiple backends..."

I understand that but my question is "if someone install UnifiedNLP, when Breezy Weather asks for location, will it get location from these network providers?"

If that's the case, we need to document step-by-step instructions for users without Google Play Services ;)

Additionally, I see there is no update since 2017, so I would not recommand it for now (looking at recent issues, I understand a new version is coming with all providers bundled in).

**Comment by LuccoJ** [comment]
UnifiedNLP is deprecated, as it has long been a component of microG while the standalone UnifiedNLP got few updates; now, microG dropped UnifiedNLP completely, because of some devilry that recent Android versions added making location-modules-as-separate-processes no longer viable, so microG now integrates location functionality rather than having a system of modules to provide it.

UnifiedNLP is dead... long live... whatever. I liked it.

**Comment by papjul** [comment]
Thank you very much for all these details!

1) Is there any network location provider app that you can install and whenever any app requests a location, it will ask this app to provide it? Basically, what standalone UnifiedNLP did, if I understand correctly how it worked.

2) If not, how is it working on Huawei devices?

3) Alternatively, is it possible to install Google NLP as a standalone app (extract APK from Google Apps bundles and install it)?

4) When I forked the project, there were 3 variants: F-Droid and Google Play didn't have Google NLP bundled, while other stores (Chinese market) did. What's interesting, but could be an error, is that the Google Play variant doesn't have it. Could this mean that we don't need this library if we already have the Google NLP installed as an app (all Google Play users have it)? If that's the case, I would prefer implementing 3) rather than bundling Google NLP for everyone!

5) Lastly, if none of these are options, implementing Mozilla NLP inside the app may be the best alternative, if I understand correctly (no need to store anything, just make API calls). I would prefer to avoid, I mean: if all apps that need location must do that, that's terribly redundant…

**Comment by LuccoJ** [comment]
Any package providing network location must be whitelisted by the system as a candidate network location provider. If the system only has Google whitelisted, other things won't work (custom ROMs usually have UnifiedNLP whitelisted).

With this proviso, it is possible to install an APK that provides network location, just like you say UnifiedNLP used to do. However, I'm not aware of any other freely licensed provider.

I have no idea if it's possible to extract the part of GMS that provides location, and personally, I don't care because I would never want to use it. Huawei probably has a "clone" of sorts, like it has a clone of most Google features. I also have no idea whether you can extract it, and likewise don't care.

If you want to avoid 5, in my view the things users expect you to do is to just use whatever is registered with the system as a location provider: they'll either be using what comes with their OEM (likely Google, maybe Huwawei stuff, maybe slightly tweaked stuff by other brands) and not caring, or they'll be using microG, either the UnifiedNLP variant or the newer Mozilla-only variant.

I think most users don't expect your app to do its own geolocating based on the cells, wireless APs and Bluetooth beacons *it* sees, as that's the system's job (or rather, the system provides an API, and it's not the app's business to mess with what's *behind* that API). At the same time, apps doing precisely this is why Google implemented the "nearby" permission, as before, any app scanning Bluetooth or WiFi would have to request location permissions, and users often didn't understand why, but the reason was that an app like that *could* theoretically determine your location based on those things.

Note that now you can also ["strongly assert"](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#declare-android12-or-higher) that your app won't use Bluetooth or WiFi access for determining location, and I assume breaking this assertion would be very bad news for Play candidacy.

**Comment by papjul** [comment]
Thank you again for all these details!

Am I right to say that:
1. All phones sold on this planet come by default with a system that includes a network provider? (let’s don’t count obscure manufacturers people never heard of)
2. The only case with no network provider is intentional choice from user (example: I install a LineageOS ROM without GApps or microG)


> Any package providing network location must be whitelisted by the system as a candidate network location provider. If the system only has Google whitelisted, other things won't work (custom ROMs usually have UnifiedNLP whitelisted).

OK, I guess that whitelisting an app requires root rights, so it’s not something I can instruct users to do.


> Huawei probably has a "clone" of sorts, like it has a clone of most Google features. I also have no idea whether you can extract it, and likewise don't care.

Yes, from what I read, Huawei made the same API as Google to ease the transition.


> If you want to avoid 5, in my view the things users expect you to do is to just use whatever is registered with the system as a location provider: they'll either be using what comes with their OEM (likely Google, maybe Huwawei stuff, maybe slightly tweaked stuff by other brands) and not caring, or they'll be using microG, either the UnifiedNLP variant or the newer Mozilla-only variant.

That would be the best situation. However, I have yet to understand why Wangdaye implemented so many network location providers if the system is supposed to take care of the situation. I don’t want to remove features that are used, or if Wangdaye ever comes back, I would prefer him not to find out that I removed important features for him.


> I think most users don't expect your app to do its own geolocating based on the cells, wireless APs and Bluetooth beacons _it_ sees, as that's the system's job (or rather, the system provides an API, and it's not the app's business to mess with what's _behind_ that API). At the same time, apps doing precisely this is why Google implemented the "nearby" permission, as before, any app scanning Bluetooth or WiFi would have to request location permissions, and users often didn't understand why, but the reason was that an app like that _could_ theoretically determine your location based on those things.

Then, why does this page exist? https://developers.google.com/android/guides/setup
Does this mean that the system will not provide network location if I don't add this lib to my app? Then, what will approximate location permission do if I don’t implement this library, as it is supposed to return network location? It seems contradictory to “that's the system's job”.

There are even instructions to automatically switch between Huawei and Google network providers, again by implementing libs: https://medium.com/@nickolajarjous333/android-location-service-for-both-huawei-and-android-devices-29bdad42bdf4


> Note that now you can also ["strongly assert"](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location) that your app won't use Bluetooth or WiFi access for determining location, and I assume breaking this assertion would be very bad news for Play candidacy.

Then, does that mean that all apps depending on AMap SDK and Baidu SDK are banned from Play Store? These are network location provider libs that require these permissions to be able to provide location from nearby devices.


I agree with you that it’s not the job of an app to determine the position from nearby devices, however why are there so many network location provider libraries available to be included in Android apps, including Google Play Services Location, if you are not allowed to publish them on the Play Store?

**Comment by LuccoJ** [comment]
Except UnifiedNLP is being deprecated...

**Comment by papjul** [comment]
Yes:
- No updates since 2017
- From next version, it will no longer be possible to install it outside microG

I think the best I can do is implement Mozilla Location Service, but that would require adding more permissions to the manifest to scan for nearby devices, so I'm not going to rush into it for now.

In the meantime, Android should take care of using its own network location provider, from my understanding.

**Comment by LuccoJ** [comment]
If you actually use nearby devices to determine location (like you would in this case), then you have to declare precise location permission, not just nearby devices, if you don't want to be kicked out of Play.

**Comment by papjul** [comment]
Closing as Android is supposed to take care of using its network location providers.

For a follow-up, see #249, we will soon add an additional IP location search, that works worldwide and seems to have fast and rather accurate results.
