### ISSUE TITLE
MET Norway: Weather data refresh fails in languages not using Arabic numerals

### ISSUE THREAD

**Issue by AlbahrawyTiger** [breezy-weather/breezy-weather#512]
### Steps to reproduce

When the application language is Arabic or any RTL language, fetching weather information from MET Norway fails and a message appears on the screen: MET Norway: Weather data refresh failed

while when the application language is changed to English, this error does not occur.

### Expected behavior

_

### Actual behavior

_

### Weather source used

MET Norway

### Breezy Weather version

4.6.8-beta

### Android version

10

### Device

Oppo a15

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I'm unable to reproduce, please:
1. give an example of city
2. send your crash log (Settings > Debug > Export crash log).

**Comment by papjul** [comment]
> > 1. give an example of city
> 
> Cairo Egypt

There are many location results for Cairo, I'm unsure which one to add, but I can't reproduce with the one I took. Can you reproduce with another city (maybe one with a less common name?)?

Curious there is no more info in crash log. When it's "Weather data refresh failed" (generic error), I always make the app print more details in logs. Did you export logs after getting the error?

**Comment by papjul** [comment]
OK, I don't know why I couldn't reproduce earlier.

The reason is that MET Norway has an endpoint for sun & moon data with a date parameter. On languages not using (Western) Arabic numerals, this leads to URL looking like this and being invalid:
https://api.met.no/weatherapi/sunrise/3.0/sun?lat=39.03171157836914&lon=-90.26122283935547&date=%D9%A2%D9%A0%D9%A2%D9%A3-%D9%A1%D9%A0-%D9%A0%D9%A7

While it should look like 2023-10-07. This is a mistake from my side, of course, as I didn't take into account other numeral systems in the world.

Will look into it!
