### ISSUE TITLE
Current Temperature Bug

### ISSUE THREAD

**Issue by Glassto** [breezy-weather/breezy-weather#522]
### Steps to reproduce:
1. Add Serbauti

### Expected behavior

The main temperature should be the same as the temperature from hourly forecast.

### Actual behavior

The main temperature is different than the temperature from hourly forecast.

### Weather source used

AccuWeather, Open-Meteo

### Breezy Weather version

4.6.7-beta

### Android version

Android 9

### Device

Samsung Galaxy Note 8

### Other details

![Screenshot_20231010-081052_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/102603092/046fc53e-eb94-46a5-bb43-ed225b444e20)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Current is based on real observation on the ground, not on hourly forecast.

Additionally, AccuWeather is known to not give us the current hour in hourly forecast (hence why 8:00 looks so different from 09:00), so we have to re-use old cached version, so if your last update was a long time ago and they change their forecast in the meantime, we can't know because they don't send it to us! Unfortunately, there's nothing we can do about that.

I don't know when you last updated, but unless it was 2 days ago, it looks like AccuWeather is very inaccurate for your place (7 degrees of difference between observation and forecast!), and you should probably use another source.
