### ISSUE TITLE
add a way to support the project through donations

### ISSUE THREAD

**Issue by Glassto** [breezy-weather/breezy-weather#531]
### Describe your idea

Adding a donation feature to your application would provide users with a convenient and secure way to contribute and show their support.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.9 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I make a living and I have no infrastructure costs, so I don't need it, and I don't want to take anyone's money, people have expectations when they pay for something. I'm doing this project for myself first, and provide it as a bonus to anyone who finds it useful with no guarantee. I want to remain free in my decision process and free to leave the development any time.

If you still have money to spare, you can support weather sources which have infrastructure costs, such as [Open-Meteo](https://github.com/open-meteo/open-meteo), the leading free and open source weather API. Pirate Weather also has subscriptions at a small fee, if you use it (it's not open source though).

Otherwise, feel free to donate to a charity or anything you like ;)
