### ISSUE TITLE
[Open-Meteo] Provide postal codes in location search results

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#55]
### Describe your suggested feature

When searching by location name with Open-Meteo as the location provider, the search results sometimes include seemingly identical entries which are actually locations with identical names located in different regions. However, the information currently provided in the app isn't sufficient to differentiate those entries.

For example, when searching for Hausen a city which exists multiple times in Germany, the results include entries that appear to be identical. Here, additional information would be needed to differentiate them properly.

If I understood the logic correctly, the [Geocoding API](https://open-meteo.com/en/docs/geocoding-api#name=hausen&count=20) from Open-Meteo provides four levels of administrative information for a location (admin1-4). In Breezy Weather, if admin2 exists, this is shown in the results. If admin2 is empty, admin1 is shown instead. admin3 and admin4 don't seem to be used currently or at least I couldn't find an example.

In the example above (Hausen), the state (admin1) is identical for some of the search results and admin3 would be needed to differentiate the locations.

<details><summary>screenshots location Hausen</summary>

![app search results Hausen](https://github.com/breezy-weather/breezy-weather/assets/97251923/13a7a9a7-15d1-4254-b846-1743285838e1)

![geocoding api info Hausen](https://github.com/breezy-weather/breezy-weather/assets/97251923/b45653e2-d737-4c65-8052-486dce0fb63b)

</details>

I don't have a good solution for this because I'd assume that always showing admin1-4 in addition to the country and location name is just too much information and it would probably need too much space in the search results list.

Maybe someone has a smart idea how to resolve this.

### Other details

AccuWeather's location search has this behavior as well, however, searching by postal code works quite well there. This effectively narrows down the number of search results. So, I don't think that it has such a great impact here.

In contrast, searching by postal code didn't work very well with Open-Meteo in my tests (with German locations, including large cities like Berlin). As a result, I think adding more regional details improves the user experience when searching by name.

<details><summary>search by postal code AccuWeather vs Open-Meteo</summary>

| AccuWeather | Open-Meteo |
| --- | --- |
| ![Screenshot_20230622-140605](https://github.com/breezy-weather/breezy-weather/assets/97251923/2fcf0b70-4354-4a62-8485-7501aa89d9d5) | ![Screenshot_20230622-140614](https://github.com/breezy-weather/breezy-weather/assets/97251923/38cda20f-28e7-4b7e-9e48-7916706cc3e8) |

</details>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by min7-i** [comment]
I'm not quite sure if all of the postal codes have already been added to Open-Meteo. Something along the lines of adding exactly that is mentioned as a todo in their repo. So, I created a new issue to ask for the current status: open-meteo/geocoding-api#8

As for showing the postal code, if a single postal code is provided, showing that would help. However, when looking at the example with Hausen, those three entries don't have a postal code. But in other cases it might be helpful.

![grafik](https://github.com/breezy-weather/breezy-weather/assets/97251923/3ac6e70e-224f-4d69-b4de-1694b59adfbd)
![grafik](https://github.com/breezy-weather/breezy-weather/assets/97251923/5c8f1de8-92a8-46e8-ac98-9ce733ae16ad)

**Comment by min7-i** [comment]
I got a reply in the Open-Meteo repo which confirms that the separate postal code source from geonames isn't used in Open-Meteo right now. (more details in open-meteo/geocoding-api#8)

Some postal codes are provided as additional information in one of the data sources (alternateNames) for the locations. That is why some locations can be found using a postal code, but others cannot.

**Comment by pdpapper** [comment]
I still think this is a useful suggestion. I mostly use AccuWeather and run into this pretty often when traveling. I didn't know I could use postal codes. That's a good tip, but I rarely know the postal code of the places I want to look up on the road. Instead of having to separately search for the code, it would be nice if there was an option for more info within the app.

It might not be useful for everyone, but for me at least, seeing the lat-lon would be enough and this info is already available since it's part of the URL sent to get alerts. Maybe, for example, long pressing a location on the list could pop up the lat-lon.

**Comment by papjul** [comment]
This is a different issue, you're looking for #10

**Comment by pdpapper** [comment]
I wouldn't really want a map, just the latitude and longitude, which are numerical values that could be popped up with a simple toast.

**Comment by papjul** [comment]
I don't think a longitude and latitude is useful without a map to most users. But even in that case, this has nothing to do with the Open-Meteo search issues discussed here.

**Comment by pdpapper** [comment]
The request was to show more details so that seemingly identical named locations can be distinguished. Latitude and longitude are one possible additional level of detail. I don't know exactly what other details could be shown. I suggested lat-lon because I know they're available but not shown.

I also suggested a way that additional details (whether lat-lon or something rlse that is available) could be shown without umnecessarily cluttering the search results.

Sorry you don't think these are relevant suggestions.

**Comment by papjul** [comment]
OP gave an example of city (Hausen), this is what it would look like if we did show lat-lon:
![IMG_20231111_060425](https://github.com/breezy-weather/breezy-weather/assets/1449159/f22c3adc-a229-4bd8-a828-b6591cab1596)

These numbers mean nothing to most people if they are not computed to be displayed on a map (and I think the number of people able to compute lat-lon in their head is very low).

In your suggestion, it would uselessly clutter the interface for most people, or if you don't like this wording, it would be too narrow of a use case/feature.

In the opposite, I don't think Google Maps has a cluttered interface when it presents multiple results with different coordinates on a map (which would be one of the ways to implement adding locations from a map).

**Comment by pdpapper** [comment]
That's why my suggestion was to use a toast popup that only appears when the search result is long-pressed. I was aware (and mentioned in my comment) that lat-lon would probably not be useful for everyone, but it was just an idea. Postal codes are also not useful for everyone, at least not without separately looking them up elsewhere.

In any case, I just wanted to draw attention back to this old and possibly forgotten issue since I had recently run into it a couple times as well. For OpenMeteo, it seems like including additional admin levels would be the best solution. Presumably for the U.S. this would include the state, which is currently not shown. Non-locals in the U.S. are not as likely to know the county, which is the level currently shown along with country.

**Comment by papjul** [comment]
Closing, this is a dependency issue; other location search sources can be used to workaround the issue; and #10 will also help in the future
