### ISSUE TITLE
Adding sunny hours more prominent 

### ISSUE THREAD

**Issue by topcaser** [breezy-weather/breezy-weather#556]
### Describe your idea

First of all: wow, what an app. Amazing work. Thanks for this and adding so much weather sources.

To judge the solar forecast it would be nice if you could make the sunny hours more prominent. Currently I have to open a day and scroll all the way down. Hard to do it per day and per weather source. Please add this info directly in front the global day information and in the hourly forecast.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.10 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
What's your use case?

Currently, Hours of sun is not provided by any source, except AccuWeather.

AccuWeather provides the number of hours when the sun is visible, while for other sources, we use the formula Sunset hour - Sunrise hour.

I was more thinking about a cloud cover chart, which would be more precise and would work with most sources. What do you think?

**Comment by topcaser** [comment]
The use case is to get a feeling about the energy forecast a solar power plant would create. A could coverage would be nice, this is even mappable to hourly forecast. The app solexpect is able to forecast the energy directly..

**Comment by pdpapper** [comment]
I would also love to have this feature, so the use may not be as narrow as you think. For me, it's just tge best way to judge how cloudy it will be. More detailed and easier to understand than the verbal or iconic ways.

I've gotten very good at flipping through the daily forecasts and scrolling to the bottom of each one, but having it as an option on the daily trend card would be great. It shouldn't be hard to have it only show as an option for AccuWeather forecasts, right?

**Comment by papjul** [comment]
It's a narrow case because only supported by AccuWeather and we don't do source-specific features.

What I can do is apply the formula used on other sources to AccuWeather, but Hours of sun will then become a redundant info with sunset/sunrise for all sources, so I wouldn't see the point of such a chart.

Hence my suggestion to use a widely supported field: cloud cover. It will be less of a narrow case as it would cover more cases.

**Comment by pdpapper** [comment]
Is cloud cover available as part of the daily forecasts and just not currently shown anywhere? I expect that would be a good solution. AccuWeather's hours of sun is probably based on that and daylength anyway, I guess.

OpenWeather forecasts already do show hours of sun, which is just daylight hours, like you described. I don't know about other sources.

**Comment by papjul** [comment]
Cloud cover exists on hourly forecast and is not currently displayed.

**Comment by topcaser** [comment]
Why is it not displayed? Is it hidden by development?

**Comment by pdpapper** [comment]
I guess the most comprehensive solution that would not be specific to any weather source is to allow any numeric info that's available in the daily forecast to be shown on the daily trend card. And I suppose the same for hourly forecast data and the hourly trend card, too.

That would make hours of sun available if you use AccuWeather and also make other data available like cloud cover, apparent temperature, etc. even if they are specific to other sources.

There already seems to be code to hide options on the trend cards if the data isn't available since the precipitation button doesn't show if there's none in the forecast.

**Comment by papjul** [comment]
A few versions ago, we added Sunshine duration tab to Daily trends
