### ISSUE TITLE
Put the weather source on top of the screen

### ISSUE THREAD

**Issue by topcaser** [breezy-weather/breezy-weather#563]
### Describe your idea

Hi, I have several weather sources for the same location. It's hard to track which weather source is currently displayed. I have to scroll all these way down. Is it possible to put that info in the name of the location (maybe abbreviated and withdraw smaller font size)? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
This app is not intended to be used to add multiple times the same location, although nothing will stop you from doing so. The reason is that we have limited usage of sources for free for all users so we ask for fair use. And when you say you can't keep track of all your same locations, it worries me about how much credits you consume.

For the purpose of comparing weather models, I would suggest checking out other services such as Windy.com
