### ISSUE TITLE
The temperature notification widget is slightly cut off on some devices.

### ISSUE THREAD

**Issue by ghost** [breezy-weather/breezy-weather#571]
### Steps to reproduce

1. Enable the notification widget and set it to show the temperature as a status bar icon.
2. See that it is slightly cut off from the right.

### Expected behavior

It should not be cut off.

### Actual behavior

The ° is slightly cut off (it doesn't show the full ° symbol).
![Screenshot_20231121_204435_Files](https://github.com/breezy-weather/breezy-weather/assets/126414307/b2324f27-8889-43f3-ace9-3a6eac0ee4df)

### Weather source used

AccuWeather

### Breezy Weather version

4.6.11-beta

### Android version

Android 13

### Device

Samsung Galaxy A51 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 4.6.11 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I can reproduce, but it's an Android SDK bug, as we make exact width measurement before creating the icon. Not much I can do :(

**Comment by min7-i** [comment]
From what I could find there is some kind of [leading space](https://stackoverflow.com/a/32081250) before the actual text starts. As a result, the text is currently positioned a bit too far to the right. This can be fixed by modifying the formula for the horizontal starting position of the text:
https://github.com/breezy-weather/breezy-weather/blob/936832710cb75dc5b89517fc5210ca2f7eac5fbe/app/src/main/java/org/breezyweather/theme/resource/ResourceHelper.kt#L171

 If you substract that space, the entire text becomes visible:
`(bitmap.width - bounds.width()) / 2f - bounds.left`

However, adjusting the formula also means that the displayed text will be a bit smaller.

You can see the difference here (left icon = new formula; right icon = current one):
![status_bar_temp_1](https://github.com/breezy-weather/breezy-weather/assets/97251923/7d25db93-24b3-4b1c-9ca7-7a8f2dff2b63)
![status_bar_temp_2](https://github.com/breezy-weather/breezy-weather/assets/97251923/a8852d98-810b-4fe7-b171-28e49cac9253)
![status_bar_temp_minus](https://github.com/breezy-weather/breezy-weather/assets/97251923/91f1a459-379d-4e2d-a093-46bcd32e87a6)

**Comment by papjul** [comment]
Thank you so much for your investigations! Your pull request will be more than welcome! :)
