### ISSUE TITLE
More detailed information about the position of the Sun and Moon

### ISSUE THREAD

**Issue by ikanakova** [breezy-weather/breezy-weather#605]
### Describe your idea

More detailed information about the position of the Sun, e.g. Civil Twilight, Dawn, and Dusk & Nautical Twilight, Dawn, and Dusk & Astronomical Twilight, Dawn, and Dusk & Golden Hour etc.

### Other details

Maybe this library could be used: https://github.com/mourner/suncalc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
You linked to a library written in JavaScript, we can't use that.

There may be other libraries we can use, but I'm undecided if it really fits the app, this is a rather specific request. All these details would probably be hard to fit nicely. And libraries running on mobile devices are usually not very accurate, they just need to be fast. Because outside of libraries, this kind of data is never (if not, almost) provided by weather sources. So, I think you will be best served by an app dedicated to astronomy both from user experience and accuracy.

There is also #213, but even that one is very low in my priority list, as it fells a bit outside the scope of the app.
