### ISSUE TITLE
Round °F temp to nearest in details view

### ISSUE THREAD

**Issue by psyburr** [breezy-weather/breezy-weather#612]
### Describe your idea

I believe that having °F accurate to more than ½ degree is outside of the scope of this weather app and crowds mobile displays with information that isn't relevant to users of the Fahrenheit scale. I understand this may be more common when using Centigrade as the scale is tighter, but it is not commonplace for Fahrenheit to be displayed in digital such as 73.8 or 24.1. I see that these temperatures are not displayed as such anywhere except for each days details page, and maybe that is the reason why it is only displayed on said page that way, but it would be nice if it was like that across the entire app as it stands out as I believe it stands out to the user for attention when it should not otherwise. I would recommend all Fahrenheit values be rounded up or down to their nearest whole number where we they are displayed within the app for a more uniform appearance. Screenshot attached to display the page and details I am referencing. 
![a893f813-3b44-4414-ae4e-ff51b499eab3](https://github.com/breezy-weather/breezy-weather/assets/38013556/f378e6d3-2759-48bf-bba9-5eb5a7d37023)

### Other details

Somewhat discussed in #138 , but just worth mentioning for possible relevancy because it isn't actually the same issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.12 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> it is not commonplace for Fahrenheit to be displayed in digital such as 73.8 or 24.1

I do find it for average and highest temperature on popular weather websites, which is the purpose of where it is currently displayed in app: https://www.wunderground.com/cat6/Death-Valley-Sets-US-Record-Hottest-Month-1080F-Average-Temperature

Which is why:

> I see that these temperatures are not displayed as such anywhere except for each days details page, and maybe that is the reason why it is only displayed on said page that way,

> but it would be nice if it was like that across the entire app as it stands out as I believe it stands out to the user for attention when it should not otherwise

Since we are on day details, and on a page with enough space, it doesn't stand out, it's on a specific page of ***details*** where knowing the record temperarure of that day to the decimal can be relevant.

Making the same experience accross all app the other way around (decimals everywhere) would clutter too much the interface, while adding little to no value, even in Celsius.

The 3rd option to make an exception to the standard behavior for only the Fahrenheit scale would require specific code for only this scale. Additionally, I would have no justification if someone reports a bug saying "when I set Celsius unit, I have decimals, but not when I set as Fahrenheit".

So, my view on this is to keep it that way as having decimals allows you to round to the nearest number in your head, while truncating to the nearest number doesn't allow you to have the detailed number.
