### ISSUE TITLE
Refresh weather on app launch when automatic refresh is disabled

### ISSUE THREAD

**Issue by brian6932** [breezy-weather/breezy-weather#632]
### Describe your idea

Pretty basic feature, alternative to constant background syncing. Personally I keep on alerts, but open the app when I need to check anything more than that, when the Dark(er) Sky app existed, it did this for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> * [x]  My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.

Please read FAQ

**Comment by brian6932** [comment]
I don't really understand the reasoning, just have a rate limit that's persisted across app launches

**Comment by papjul** [comment]
The app-side rate-limit across app launches is the automatic refresh rate.

Example: your automatic refresh rate is set to 1.5 hours. You open the app, while location was last refreshed 2 hours ago => app will refresh automatically on app launch. Usually, this case should not happen since background syncing should have updated weather 30 min ago.

I guess from your message that you're in a special case: you set your automatic refresh rate to Never, right? You also say you want to be notified of alerts. Alert notifications only happen with automatic refresh (background syncing), because if there is no syncing, app is never aware of newer alerts of course. This is one of the reasons I don't recommend completely turning off automatic refresh (put a refresh rate of 12 or 24 hours instead).

Would an automatic refresh on app launch if last refresh > 1.5 hours ago AND automatic refresh rate = Never be helpful to you?

**Comment by brian6932** [comment]
No because my issue is that I still want alerts

**Comment by papjul** [comment]
There is no task for alerts emitting since weather refresh is a pre-requisite so all happen in the same task: notifications of alerts are emitted at the end of the weather refresh process.

There is only three types of background tasks:
- Automatic refresh (periodic)
- Today notification (at a specific time)
- Tomorrow notification (at a specific time)

**Comment by k3dar** [comment]
I too like this having thisfeature, i'm here to create issue for it and found this ;⁠-⁠)

My use case is:
- auto sync set to newer
- don't use widget
- only manually run app

And now, always after run app i'm manually doing pull down fo refresh.
Be fine if added option "Automatic refresh when app launch" :⁠-⁠)

**Comment by papjul** [comment]
> Would an automatic refresh on app launch if last refresh > 1.5 hours ago AND automatic refresh rate = Never be helpful to you?

I will do it like that. If less than 1.5 hours ago, you can still force pull to refresh.

Note that Notifications of alerts and precipitations are only possible with a task in background of course, so I will also grey the options and add a note to explain why.
