### ISSUE TITLE
[Location list] Animation stutters when scrolling down

### ISSUE THREAD

**Issue by min7-i** [breezy-weather/breezy-weather#70]
### Steps to reproduce

1. Open the location list.
2. Make sure that you have multiple locations in the list so that you can actually scroll down. On my device that's about 10 locations.
3. Scroll down to see the locations at the bottom of the list.

### Expected behavior

The list should smoothly scroll down. Depending on the intensity of the scroll gesture it should scroll faster until reaching the bottom of the list.

### Actual behavior

The scrolling animation is stopped / stutters when scrolling down.

It's hard to see in the screen recording, but when trying it yourself you should be able to see what I mean. (In the recording I did a full scroll down gesture which should have been enough to reach the bottom of the list.)

https://github.com/breezy-weather/breezy-weather/assets/97251923/45d5cec3-e7ad-468d-b944-9f1786c8c6c1

### Weather provider used

not relevant

### Breezy Weather version

4.0.1-alpha

### Android version

Android 13 (GrapheneOS)

### Device

Google Pixel 6a

### Other details

This actually seems to be linked to the heading "Locations" that is moved into the top app bar when scrolling down. When moved into the app bar, the scrolling animation is abruptly stopped. Once the heading is displayed in the app bar scrolling down works smoothly again.

The app [seal](https://github.com/JunkFood02/Seal/) uses a similar layout where the heading is moved into the top app bar (although the view is used for settings). If I'm not mistaken, the app uses material 3 as well. So, if you need some reference, looking at that app might help.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to **[latest version](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
All top bars in the app are implemented that way, there is the same "issue" in Settings if you look carefully.

It comes from the compress effect, that is an animation that pins the title to the top, which results in the scrolling being slightly slowed down as the animation effect takes place.

It is an intentional behavior, as described in the Material 3 guidelines here: https://m3.material.io/components/top-app-bar/guidelines

"When scrolling up, Medium top app bars can use the compress effect to transform into Compact top app bars. They should not return to Medium size until the user scrolls back to the top of the page."

Seal uses `TopAppBarDefaults.pinnedScrollBehavior()` while this app uses `TopAppBarDefaults.exitUntilCollapsedScrollBehavior()`. I'm not familiar with these behaviors, but the Seal implementation lacks a fade in/out for title (if you scroll slowly, you will notice title appearing twice).

So I have no suggestion. Maybe future versions of the Android Material library will reduce the stuttering, I don't know…

**Comment by min7-i** [comment]
The stuttering that I experience in the location list doesn't happen in settings. In settings I can easily scroll down to the bottom of the settings with a single gesture. I can't do that in the location list.

I really have to swipe up aggressively to reach the bottom of the list in one swipe. In settings that isn't the case. Scrolling is a lot smoother there.

**Comment by papjul** [comment]
I already spend a lot of time investigating this, tagging "Help wanted" in case someone wants to pick it up.

**Comment by min7-i** [comment]
Thanks for looking into it. Normally, I don't have so many locations. I was just testing out some stuff and that's when I noticed it.

> That is a different issue than the stuttering that can be reproduced by doing a slow finger gesture; now, you're talking about a swipe.

Then I didn't explain it very well. Sorry for the misunderstanding. That "second issue" is actually the original issue I was talking about.

> With a single "normal" swipe, I can easily scroll to the bottom of the list. Of course, the scroll animation will slow down as the title bar compress as we explained above, but there is nothing preventing the scrolling.

I understand that the slow down works as designed, but that's not the issue I'm talking about. From what you're saying I'm actually not sure if you're experiencing the same on your device as I am on mine.

I can just say that for me the scrolling experience is way better in settings than in the locations view.
