### ISSUE TITLE
Ability to set default main weather source

### ISSUE THREAD

**Issue by popogomo** [breezy-weather/breezy-weather#711]
### Describe your idea

Thanks for the best weather app out there!

When we add a new location, it always asks to select Main Source, Air Quality source, Pollen source, Precipitation minute by minute source, Alerts source and Temperature normals source, so we need to select these every time.

It will be great if we could have an ability to define the settings we want to it will automatically use these when adding a new location without bringing the prompt every time. For example, in my case, I use Open-Meteo for everything and "None" for Alerts and Temperature Normals, so I want it to remember this and never ask again when selecting a new location.

Hope this makes sense. Please give me a shout if you require more info. 

Thanks again for such a great app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The pre-selected sources depends on the country of the location you tapped on, you can see how it's done here (I think the code is self-speaking for a non-developer): https://github.com/breezy-weather/breezy-weather/blob/v5.0.1-alpha/app/src/main/java/org/breezyweather/common/source/LocationPreset.kt

It may be confusing to offer an option to customize the `DEFAULT` but not other countries, so I’m not sure how that would fit. Will put this in Undecided state, but let me know if you have any ideas!

**Comment by papjul** [comment]
But in that case, if you want to check the weather in - let's say - Germany, it's best to use DWD source, not the same source that you used for the previous country - let's say - France, where you used Météo-France.

What you want is the ability to turn off any suggestion for any country, right?

And then, you want the app to remember your last selection? But what if your last selection was DWD but you then add a location from Norway? DWD is not available in Norway, only in Germany.

I understand the annoyance, but there doesn't seem to be an easy solution to that problem.

**Comment by papjul** [comment]
The only solution I have in mind is to add a preference in:
Settings > Weather sources.

Default weather source when adding a location:
Automatic
Always use Open-Meteo
Always use AccuWeather
Etc
*(Only worldwide sources listed here)*

You will have to go to Settings, and it won't cover all cases (what if you always want to add cities from France using Météo-France AND always with Open-Meteo as air quality and pollen source? You can't set secondary sources with that preference)

So, I'm still a bit undecided, that still looks complex to cover a narrow case (although that would allow to get a similar behavior to versions prior to 5.0). At the same time, I acknowledge there is an annoyance, so let me know what you think or if you have other ideas?

**Comment by ikanakova** [comment]
The ability to set default sources would be really great! I think a lot of people use the app daily for multiple locations in one country rather than multiple countries. For example, I have for my home town, for work, and a for a cottage, and I often travel to different cities in my country. When I travel out of the country a few times a year it is easier for me to adjust the sources than to select the same sources for locations in my country each time.
It could be done so that if someone checks in the settings that they want to remember the default sources, it will remember it after the first time the location is set, and then it will be set the same each time for Main Source, Air Quality Source, Pollen Source, etc.

**Comment by ikanakova** [comment]
> > It could be done so that if someone checks in the settings that they want to remember the default sources, it will remember it after the first time the location is set, and then it will be set the same each time for Main Source, Air Quality Source, Pollen Source, etc.
> 
> This isn't possible, because of:
> 
> > if your last selection was DWD but you then add a location from Norway? DWD is not available in Norway, only in Germany.

But I think that if the bottom was Edit like other locations with the correct source, the user could easily change the incorrect source to the correct one.

**Comment by papjul** [comment]
That would replace an annoyance with another annoyance, that would be confusing for many users. App shouldn't allow incompatible sources to be set up in the first place.

**Comment by ikanakova** [comment]
> That would replace an annoyance with another annoyance, that would be confusing for many users. App shouldn't allow incompatible sources to be set up in the first place.

I agree with that, but that means that Oslo with DWD shouldn't be able to be added at all and not be added and pop up a Weather refresh failed message like it is now. Which I think is far more annoying than if it was added with option to change the wrong source.

**Comment by papjul** [comment]
> I agree with that, but that means that Oslo with DWD shouldn't be able to be added at all and not be added and pop up a Weather refresh failed message like it is now.

Currently, there is no "Weather refresh failed" about that, because DWD is not an option when you add Oslo. You can't choose DWD as a source. Unless you want to allow it, which is not just an annoyance for the user that don't understand why DWD is suggested in the list if it's not compatible for the country, but also an annoyance for the weather source to receive incompatible network requests.

So, if DWD is not in the list and your last remembered choice is DWD, what do we put as pre-selected source instead? For example, if my last remembered choice is:
- Main source: DWD
- Air quality: Open-Meteo

What should I suggest for a city in Norway? A mix of last remembered and suggested sources for Norway?
- Main source: MET Norway (as suggested for Norway)
- Air quality: Open-Meteo (as last remembered)
?

Or, if any of last remembered is incompatible, fallback to only suggest sources for all of them?
- Main source: MET Norway (as suggested for Norway)
- Air quality: MET Norway (as suggested for Norway)

Both cases are very confusing in my opinion!

**Comment by ikanakova** [comment]
> Currently, there is no "Weather refresh failed" about that, because DWD is not an option when you add Oslo. You can't choose DWD as a source. Unless you want to allow it, which is not just an annoyance for the user that don't understand why DWD is suggested in the list if it's not compatible for the country, but also an annoyance for the weather source to receive incompatible network requests.

I can imagine a user adding a location with the sources they are used to (I MET Norway for example) and not always checking if it is compatible with the country. For example, I didn't know DWD before and when I tried to add Oslo, DWD was listed as one of the possible weather sources, even though it didn't work then and just popped up an error message:
<img src="https://github.com/breezy-weather/breezy-weather/assets/38765251/6a92d9cf-9723-4e61-bfaf-70cbbcfa67c2" width="500" alt="Screenshot_20240227_104645_Breezy Weather">

People from Germany probably know that DWD doesn't work elsewhere, and people from the Czech Republic like me probably wouldn't even choose this source for Germany because they are used to MET Norway or AccuWeather etc.

> So, if DWD is not in the list and your last remembered choice is DWD, what do we put as pre-selected source instead? For example, if my last remembered choice is:
> 
> * Main source: DWD
> 
> * Air quality: Open-Meteo
> 
> 

I think it should be that when someone adds Oslo with DWD (either by themselves or it's automatically added with default sources), it pops up a message that they need to change the source because it's not compatible with that location + Help me choose.

**Comment by papjul** [comment]
Ah, yes, you're right, you can choose an incompatible source in main source, but not in other secondary sources. Will fix that!

**Comment by papjul** [comment]
Can you let me know if the proposition in [this comment](https://github.com/breezy-weather/breezy-weather/issues/711#issuecomment-1965949962) would fit you?

**Comment by papjul** [comment]
Yes, I'm looking for a solution that is neither too complex to understand from user-experience, and not too complex to implement from technical side. I think we have a good compromise on that one :)
