### ISSUE TITLE
Add small paddings between each weather sources credits

### ISSUE THREAD

**Issue by MatsG23** [breezy-weather/breezy-weather#725]
### Describe your idea

At the bottom of the homescreen, you can see all the credits for weather data sources. However, the expanded list is complicated to read because they credits are shown in one big text box without any seperators:
![Screenshot_20240301-153643](https://github.com/breezy-weather/breezy-weather/assets/60609373/a522c4ff-8452-49c2-94be-310772314fc5)
![Screenshot_20240301-153646](https://github.com/breezy-weather/breezy-weather/assets/60609373/997eeb2a-f998-41c0-9d1f-f4a549086e3e)

I think this could be improved. I really like how the various contributors are listed in the About page of the app. The credits list could probably use a similar style. Maybe a dialog could fit there?
![Screenshot_20240301-154220](https://github.com/breezy-weather/breezy-weather/assets/60609373/d052ae21-693c-4df5-84d7-98eaa1e25049)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.14 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't think any of the changes you suggested would improve the situation for Open-Meteo air quality/pollen data (which I believe is the main point of frustration here, although I believe most people never expand credits to more than 3 lines, so that's really minor). That one is just a big block of texts because there are so many agencies around Europe to credit. I even had to make a special logic to merge air quality and pollen credits so we avoided having twice the same credit, once for air quality and once for pollen.

I don't know if expandable cards exist. If they do, please let me see first how that would look. If you plan on making a change here, please take into account #311 (a proof-of-concept with AccuWeather logo will be enough for the pull request, no need to create all the logic for each source).

**Comment by papjul** [comment]
> It would be beneficial to know if the info must be presented on the main screen or not.

Yes, @min7-i said it in a previous message.

I don't know about requirements for all sources but at least Copernicus says:

> All users of data uploaded on the Atmosphere Data Store (ADS) must provide **clear** and **visible** attribution to the Copernicus programme and are asked to cite and reference the dataset provider.

I would say that even the expandable text is borderline with this rule, since technically it’s not *visible* right away. So I don't want to hide it even more in a dialog.

> However, I can understand if you have more important issues to deal with. I do not know if someone reads those credits.

Well, as I said earlier, I really don’t care about those credits and I actually think most people feel the same, except a few people like you who care about it. It’s like terms of service, (almost) no one read them, so designers don’t spend time making fancy design for the terms of service page for a few people xD

**Comment by papjul** [comment]
Yes, I agree that a small padding between each credit would be good to improve readability, but that would mean getting rid of the expandable text library we use and make our own, that's not a trivial task.

I will leave this open to contributions.

**Comment by papjul** [comment]
Moving as part of #311
