### ISSUE TITLE
Remove precipitation probability bar on temperature chart

### ISSUE THREAD

**Issue by Marko-98** [breezy-weather/breezy-weather#739]
### Describe your idea

I'd recommend to change the way expected precipitation is shown in hourly and daily forecast.

Currently, behind the temperature graph, vertical bar is showing expected amount of rainfall. That sometimes makes the low/night temperature hard to read. 

Example:
![issue](https://github.com/breezy-weather/breezy-weather/assets/129692860/b8ef6d5b-ab22-4f47-9dd3-9d9e09516699)

I think it would be good idea to get rid of the vertical bar and instead put the rainfall above icon or at the bottom, in user defined measuring unit. I was thinking something like this:

![solved](https://github.com/breezy-weather/breezy-weather/assets/129692860/ac05368f-cd02-4347-85ea-c3c1335cdab1)

I'd leave the bars in precipitation tab of the daily forecast, but instead of green color, I'd paint them light blue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Your pill suggestion can be harder to read IMO, as it is even smaller. Also, remember accessibility. Some people set up their Android text size to bigger size, which would truncate it.

I can move them to the Precipitation tab but the problem is that some sources don't have precipitation quantity, only probability, so some people will miss it because they don't have the Precipitation tab.

I can try making the text slightly more white so we can read it more easily.

> I'd leave the bars in precipitation tab of the daily forecast, but instead of green color, I'd paint them light blue.

The color depends on a scale that is common to other types of data (UV index, cloud cover, etc) where basically, green = good, yellow = fairly good, orange = moderate, and so on.

**Comment by Marko-98** [comment]
@papjul How about the first solution, with the umbrella? If umbrella icon would make a problem, just blue text would be fine. 

Is there a way to remove those vertical bars in settings or those currently can't be removed?

**Comment by papjul** [comment]
> How about the first solution, with the umbrella?

I was talking about both solutions. Btw, I don't understand the unit on these screenshots, because the vertical bar represents the probability of precipitation, not the quantity (you put “mm” in your screenshot).

> Is there a way to remove those vertical bars in settings or those currently can't be removed?

There is no preference for that, but if you self-compile, you can add a 5th parameter here:
https://github.com/breezy-weather/breezy-weather/blob/main/app/src/main/java/org/breezyweather/main/adapters/trend/DailyTrendAdapter.kt#L51-L56

Right after `SettingsManager.getInstance(activity).temperatureUnit`, you can add `, showPrecipitationProbability = false`.

**Comment by Marko-98** [comment]
@papjul

> Btw, I don't understand the unit on these screenshots, because the vertical bar represents the probability of precipitation, not the quantity (you put “mm” in your screenshot).

Usually, weather apps have quantity presented along with probability. So people will know if there will be huge rainfall or small which will go away after a few minutes. And I thought those bars represent quantity, not probability. 😐 
In that case, honestly, those bars are basically useless because above the weather icon is probability percentage. I'd rather have just probability percentage and quantity somewhere instead of probability 2x.

> There is no preference for that, but if you self-compile, you can add a 5th parameter here:

Huh, I'm not into app development so I have no idea how to compile an app. 🤷‍♂️

**Comment by papjul** [comment]
> Usually, weather apps have quantity presented along with probability.

Yes, but you're on the temperature chart here, so it's just a convenient bonus to see both temperature and precipitation probability, especially as there is already a bar for quantity on precipitation chart.

But I agree with you that having precipitation data on the temperature chart can be a bit confusing, not that it is something I heard about recently from someone else, but still.

> In that case, honestly, those bars are basically useless because above the weather icon is probability percentage. I'd rather have just probability percentage and quantity somewhere instead of probability 2x.

All line charts and bar charts are both represented visually AND with data in Breezy Weather. Doing something opposite only here would be confusing, not counting that they need each other to be accessible. The text needs the visual representation to be easier to understand, and the visual representation needs the text to know what we are talking about. Example: the line chart would be pointless if we removed either the temperature text or the line.

I know there are a lot of requests about different presentations (in app or in widgets), and I'm working towards modularization of the app so that any developer can make their own presentation! No ETA though.
