### ISSUE TITLE
AccuWeather disable yellow alerts

### ISSUE THREAD

**Issue by ve1mi** [breezy-weather/breezy-weather#772]
### Describe your idea

This is really bad, all 3 alerts for the AccuWeather source write NOTHING + no ru translation.  I want to turn off alerts for AccuWeather because it's useless and just annoying.

### Other details

![Screenshot_20240310-043717_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/45261656/be597434-44a7-437f-8962-610ad5db23c5)
![Screenshot_20240310-043738_Breezy Weather](https://github.com/breezy-weather/breezy-weather/assets/45261656/90c616d7-8a42-457f-ae65-a2a297e23a69)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Two different things:
- Accuracy of alerts: you can change Alert source in Edit button at the bottom of main screen.
- Being notified of alerts with low severity: tracked as #208

**Comment by papjul** [comment]
Looks like the issue is not AccuWeather's fault. See the original alert:
- In English, you don't have a description, only "Other dangers" https://meteoinfo.ru/hmc-output/cap/cap-feed/en/20240310071602-8.xml
- In Russian, you have "На дорогах местами гололедица" as description for the same alert: https://meteoinfo.ru/hmc-output/cap/cap-feed/ru/20240310071602-8.xml

There are plans to implement national sources as part of #703 but it may be too complex for Russia since there are 83 alerts right now and opening a different link for each one of them to check the polygon would be too important.
