### ISSUE TITLE
Provide more accurate location in China

### ISSUE THREAD

**Issue by wsmmsh** [breezy-weather/breezy-weather#775]
### Describe your idea

Now breezy-weather provide a location based on district in China, not based on street.The app Weawow can provie more accurate location based on street.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I don't think I understand your request, are you talking about:
- more detailed reverse geocoding?
- or street-based weather rather than street-based location?
- or something else?

In either case, which source are you using?

We always query the weather based on your longitude, latitude, although some sources resolves that to the nearest city/district, but that's nothing we can change.
