### ISSUE TITLE
Name of a manually added location changes after 1st refresh

### ISSUE THREAD

**Issue by jfk93260** [breezy-weather/breezy-weather#776]
### Steps to reproduce

1. Search for Paris, France
2. Select either GeoNames, Open-Meteo or AccuWeather as Location search source
3. Select Paris - France, Paris or Paris - France, Ville de Paris in the results
4. Select either one of the weather providers as the main source

### Expected behavior

Paris as a whole city should be used to display weather. Ideally, Breezy weather would behave like 4.6 version and display each and every arrondissement of Paris (from 75001 up to 75020) as well as Paris as a whole (75000) and let you select the result you want to use.

### Actual behavior

A random arrondissement/district is used : for example, Météo-France always uses Paris - 4e arrondissement or Paris - 5e arrondissement. AccuWeather always uses Saint Merri or Notre-Dame. I can select a specific arrondissement if I am that way inclined: I just need to search for Paris 75017 for example, but that's not what I'd like.

### Weather source used

Any

### Breezy Weather version

5.1.0-beta

### Android version

Android 14

### Device

SONY Xperia 10 IV 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Paris is a big city. Even if you decide to only display "Paris", it's not neutral. A location is a longitude and latitude. If the center point of Paris is 4th arrondissement, then it's normal the reverse geocoding finds 4th arrondissement.

I'm not sure to understand what bothers you but I believe the following are ways that can help you:
- Don't reverse geocode if the location was just added (that way, it keeps the name from the search result). It will still reverse geocode if you change main weather source.
- Allow to customize the name of the city so that you can manually shorten "Paris 4th arrondissement" to only "Paris". It's already tracked as part of #752

**Comment by jfk93260** [comment]
I'll try to explain my point a tad more precisely:

As it is now, the location selector randomly selects the arrondissement on its own volition. The 5th arrondissement is NOT the center of Paris, still that's "sometimes" what I get. Or the 4th arrondissement... Anyway, as you said, Paris is a big city, so center or not, it's not the entire problem.

What bothers me are two things:

1. If you check the weather on Météo-France website, our main weather provider, you'll be able to either check the weather for each and every arrondissement or for the whole town, and that's for a reason: the weather is not always exactly the same across the town. It may rain in a specific arrondissement but not in another one (like today). But you also might want to check average values for the whole town if you prefer, hence the 75000

![Screenshot_20240311-153652-picsay](https://github.com/breezy-weather/breezy-weather/assets/30798957/d9692a0e-94bd-4f38-974c-3f40883a9d63)
(And so does AccuWeather by the way, I just checked their website)
Am I sure that when your location selector chooses the weather for the 5th arrondissement it actually shows me the weather for 75000?

2. Geometric Weather used to list these different choices, it was simple and clear. You searched for Paris and YOU decided which result you wanted on display.
As I wrote before, I can manually input the arrondissement I want but trying 75000 gives me no result, though. 
So, in the end, if it does actually give me the weather for the whole town and not for a specific part of Paris, then you have all of my apologies. But with all of these different possible combinations giving me different results, different names and different districts I'm pretty confused 😕

**Comment by papjul** [comment]
That's not how most API work.

Behind the scenes, a location is a longitude and a latitude.

When we ask Météo France API to provide weather forecast, we don't say "hey Météo France, give me the weather for Paris", we say "give me the weather for 48.85341, 2.3488"

That's because weather models are generated are on a grid. Especially with Météo France where some models can be as precise as a 1 km x 1 km grid, for example in the "precipitation in the next hour" feature.

So, when you ask for weather for Paris on Météo France website, on Breezy Weather 4.6 or on Breezy Weather 5.1.0, you will always get the weather for the grid that contains the center point, not average values for all grids in Paris (what would "average" even mean when it's raining at 16:00 in the West of Paris and at 17:00 in the East of Paris?). There may be slight differences as Paris center point may be slightly different, but in the end, you get the idea.

In the end, 48.85341, 2.3488 can be translated in the following human-readable forms (called reverse geocoding process):
- Paris
- Paris 4th
- Notre Dame
- Rue d'Arcole
- Parvis Notre Dame

They are all the same as long as latitude and longitude are the same. It's just a name to be more convenient to read in the app. But what matters is the longitude and latitude.

**Comment by papjul** [comment]
Paris will now stay Paris. Fix will be available in next version.
