### ISSUE TITLE
Change Details Card to 2-cols view?

### ISSUE THREAD

**Issue by k3dar** [breezy-weather/breezy-weather#779]
### Describe your idea

Actually Details Card show in 1-cols view,
what about change it to 2-cols view similar as is Pollen Card?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I thought about it, but sorry, I have too many complains everytime something is in columns.

See #539 for Pollen card
See #771 for header
Not counting reports received outside GitHub

When I replaced old v4.x header with v5.x small details, I got feedbacks from a few people that preferred the old design (especially people with accessibility settings enabled). So I told them to remove all details in header so they would move to the details card where each detail is on one row. So that card will stay that way.
