### ISSUE TITLE
Add a pollen keyword for widget custom subtitle

### ISSUE THREAD

**Issue by Jokkaj** [breezy-weather/breezy-weather#782]
### Steps to reproduce

Howdy, I could not find any guide on the internet detailing a whole list of codes for customizing widget subtitles, (I am speaking of like $cuv$ for UV index and $w$ for day of the week) is there a specific code for tree pollen count or pollen count in general?

### Expected behavior

pollen count in widget

### Actual behavior

no pollen count in widget

### Weather source used

AccuWeather

### Breezy Weather version

last one

### Android version

14

### Device

pixel 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.0.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
> I could not find any guide on the internet detailing a whole list of codes for customizing widget subtitles

This is a Geometric Weather/Breezy Weather-specific feature, you won't find a list on Internet. The list of available codes is directly in app, below the "custom subtitle" field.

I won't add a keyword for each of the 21 pollens we currently support, but I can add 1 keyword that is a summary of all pollens comma-separated.
Something like that:
Tree: Low, Mold: Moderate
While skipping any that is at "no risk" level, so that we don't get a list of 15 pollens at level 0 and only the 3 that are relevant.

**Comment by papjul** [comment]
You can use $0pis$, $1pis$, etc, as the pollen keyword. However, it's not yet compatible with Recosanté (will show wrong values), so I leave the issue open for now and don't make the keyword visible in app for now
