### ISSUE TITLE
Notification-widget is collapsed on lockscreen

### ISSUE THREAD

**Issue by Moostek** [breezy-weather/breezy-weather#793]
### Steps to reproduce

Hello, I have changed the way for a while what show in the Widget, I changed the Widhet setting "Style" from Daily forecast to Native and Location, just to try how does it looks like. But I changed it back. When I am in the OS, the Widget looks fine, with 5 days forecast, but on locked phone after I push the ON button to wake up the display and swipe down, the Widget is limited to Location I guess and I miss 5 day forecast in this phone locked status. Can you fix it, please? 

### Expected behavior

The Widget should be the same in phone locked status as well in active OS environment. 

### Actual behavior

Not same content of the Widget in phone locked status vs. active OS environment. 

### Weather source used

Open-Meteo (F-Droid version)

### Breezy Weather version

5.1.3 Beta

### Android version

Android 9

### Device

Lenovo S60

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
If you are talking about the notification-widget, please mention it in your ticket.

If that's the case, it is neither a bug or an app issue. We just send the notification, we have no control over how the lockscreen app shows notifications. Please check if you have an Android setting that allows you to have notifications expanded by default on the lockscreen, otherwise please contact your lockscreen app provider.

Otherwise, if you are talking about a widget, the answer is almost the same. We don't control how widgets are displayed on the lock screen. If there are display issues of widgets, please contact your lockscreen app provider.

**Comment by Moostek** [comment]
The Notification widget in lockscreen is reduced compared to one in active OS. On my Android (LineageOS) I just use the hiding sensitive information settings for the lockscreen.  I guess that there must be some way to control it, because **similar weather app show Notifaction Widget exactly the same in both lockscreen and active mode**. And **Geometric Weather did it as well !** 

Why did you close the issue? From my point of view **it is a bug**. Because **other similar apps show the Notification Widget with same content in lockscreen as well in active OS**.

**Comment by papjul** [comment]
Please show screenshots of normal notification vs lockscreen of Breezy Weather and of a different weather app where it works.

**Comment by Moostek** [comment]
![LOS_Screenshot_01](https://github.com/breezy-weather/breezy-weather/assets/59518454/3abc1766-2320-4b15-a24b-1e18dd65d73b)

Here it is. In the lockscreen the weather forecast is reduced just for actual temperature. Normally I can see 5-Day forecast in active OS.

**Comment by papjul** [comment]
You didn't send a screenshot of Geometric Weather with notification expanded by default on the lockscreen.

I installed Geometric Weather v3.102 and I see absolutely no difference.

Both notifications are collapsed by default on the lockscreen.

**Comment by Moostek** [comment]
Here I can show you what I have on my mind after I get another notification for Breeze Weather

Fig.1) Instead of to see full Notification Widget content on both lockscreen and active OS, which looks like this...
![LOS_Breezy Weather_Nw_03_OS_orig](https://github.com/breezy-weather/breezy-weather/assets/59518454/86d657ca-5023-45bb-b4c7-c4fd1764a40d)

Fig.2) ...I can see in lockscreen this reduced/collapsed version of Notification Widget. 
![LOS_Breezy Weather_Nw_01_Locksreen_reduced](https://github.com/breezy-weather/breezy-weather/assets/59518454/da06b32f-194d-400a-b4dd-1601f9ab5ee7)

Fig.3) And in active OS it looks like this... 
![LOS_Breezy Weather_Nw_02_OS_reduced](https://github.com/breezy-weather/breezy-weather/assets/59518454/2bfc89b8-0151-4f50-b065-f643bab5f348)

So again, the problem is that when other notification will arrive, the Breeze Weather stripe is collapsed and since then I can not see 5-Day forecast at the first glance.

**Comment by papjul** [comment]
You're talking about two things:
1) Display issue on fig 2: this was fixed in later versions of Android/LineageOS
2) Notifications are collapsed when there is more than 1 notification: I'm pretty sure this is a standard Android behavior, but maybe you can ask Google or LineageOS for a new option to always show notifications expanded on lockscreen?

I just tried Geometric Weather 2.608 but this version has the exact same problem, and it's even worse since it doesn't offer an expand button:
![IMG_20240314_174946](https://github.com/breezy-weather/breezy-weather/assets/1449159/7a85c5bb-31ac-45e4-b33c-703c01990673)

**Comment by Moostek** [comment]
Fig.2 "lockscreen" collapsing issue: 
I will check the other app and tell you later how it goes with it. 
Biut regarding to GW v2.608, yes, it seems you are right, because as I remember I did not use the Daily forecast on v2.608, so I always watched on full Notification Widget with 5-Day forecast;) 

Fig.3 "active OS" collapsing issue "797" (https://github.com/breezy-weather/breezy-weather/issues/797)
So do you think this issue can be resolved?

**Comment by papjul** [comment]
#797 needs review (with a low priority). It will be updated when the review will be done.
