### ISSUE TITLE
Settings to change the background and font/icons colours of Notification Widgets

### ISSUE THREAD

**Issue by Moostek** [breezy-weather/breezy-weather#794]
### Describe your idea

Hello, I would really like to see **in the Settings an ability to change the background colour and colour of the font/icons**. Now there is just white background which is really annoying to my black theme. Can you implement the option to change the colours of the main bar Widget, please? 

1) Background Widget colour to any colour (esp. black, dark grey or grey) 
2) Colour of the font/icons

In Geometric Weather it was possible. I would to see it here, too. 

Thank you. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
We usually offer that kind of option. Which widget are you talking about?

**Comment by Moostek** [comment]
I am talking about the Notification Widget, under the main Android status bar (I am sorry I did not write it correctly). I have not found in Settings the setting for changing colours (background & font/icons) of the Notification Widget. Can you tell me, where can I set up these colours? In the "Widget and live wallpapers" section, there is no colour scheme setting. In Geometric Weather it was possible to change the colours to dark coulours.

**Comment by papjul** [comment]
I'm not sure to understand you, can you show me an example of screenshot of Geometric Weather not customized vs Geometric Weather vs customized background/font/icons vs Breezy Weather? And a screenshot of where you found the settings to customize notification.

**Comment by Moostek** [comment]
Here is the colour settings from Geometric Weather. Check the "Barva oznámení" (Colour of notification). All those settings are just about Notification Widget. In Geometric Weather it is called "Oznámení" (Notification). It will be nice to have it in Breeze Wather too. 

![LOS_Geometric Wather_Settings_colours 01 1](https://github.com/breezy-weather/breezy-weather/assets/59518454/f93fccbc-93a9-4b21-8304-62c4976eda7d)
![LOS_Geometric Wather_Settings_colours 02 1](https://github.com/breezy-weather/breezy-weather/assets/59518454/34ce1881-1022-424d-b3a4-36ea6bf573ea)
![LOS_Geometric Wather_Settings_colours 03 1](https://github.com/breezy-weather/breezy-weather/assets/59518454/5da9c94c-fb94-4a98-8dad-8286df3ebaf9)
![LOS_Geometric Wather_Settings_colours 04 1](https://github.com/breezy-weather/breezy-weather/assets/59518454/bae6e81d-b48d-4aad-a77d-b42389933d47)

I would like to send you the screenshot of Geometric Weather Notification Widget in dark colours, but I am unable as the app is not able to search for any city. But you can conclude from the colours, what colour options are possible here (background + text/icons). It looked very smooth and nice.

**Comment by papjul** [comment]
Please send screenshots with app language in English.

**Comment by Moostek** [comment]
In GW app there is no option to select the language and I do want to change my OS to English to avoid some localization bugs. But yeah, I translated it with online OCR translator;) Here it is: 

![LOS_Geometric Wather_Settings_colours 01 1 translated](https://github.com/breezy-weather/breezy-weather/assets/59518454/fa13e191-6038-49b3-baf0-874c28953559)
![LOS_Geometric Wather_Settings_colours 02 1 translated](https://github.com/breezy-weather/breezy-weather/assets/59518454/c6ed1fb2-bf4c-4316-8e30-834db977ee70)
![LOS_Geometric Wather_Settings_colours 03 1 translated](https://github.com/breezy-weather/breezy-weather/assets/59518454/4373705f-75a4-49b5-9731-84b816326bbb)
![LOS_Geometric Wather_Settings_colours 04 1 translated](https://github.com/breezy-weather/breezy-weather/assets/59518454/3362b9dd-8d88-41f5-a228-37ff21b4ca58)

**Comment by papjul** [comment]
You can change language in Geometric Weather from Settings > Appearance > Language (at the bottom)

**Comment by Moostek** [comment]
Ah, I do not use GW anymore, I just installed this for this case, so I missed this. But the OCR translations are correct, I guess.

**Comment by Moostek** [comment]
Ah, now I can see what is the problem here;) I am talking about the version v2.608 from mbestavros (he was forked by WangDaYeeeeee). This version was released around 2020/10. This version has colour settings, so I guess later it was dropped. I can send you this old version, but I guess you can download it somewhere.

**Comment by papjul** [comment]
Ah yes, v2.608 is 4 years old. The fork of mbestavros was discontinued because we were able to merge F-Droid requirements back into the original repo.

A lot of things changed since then and I believe this feature was removed to get back to a more standard behavior now since Android added dark mode and other things like that.

However, I installed Geometric Weather v2.608 and I can't find the same settings. I can change language to English in this version but can't find notification colors:
![IMG_20240314_164219](https://github.com/breezy-weather/breezy-weather/assets/1449159/4c32f8be-35d4-463f-a847-2c0d7e1f7e8f)
![IMG_20240314_164229](https://github.com/breezy-weather/breezy-weather/assets/1449159/f66324c9-b4e3-407f-bfe7-11df02c2f996)

**Comment by Moostek** [comment]
My version is also 2.608: 

![LOS_Geometric Weather 2 608_info](https://github.com/breezy-weather/breezy-weather/assets/59518454/d225c968-2612-4544-9e06-4a41a64eea79) 

Yes, I can see now, I can change the language in 2.608 too;) 

The Notification Widget colour settings is in the section "Notification" > "Notification colour", this is it.

**Comment by papjul** [comment]
Where do you see "Notification colour" on my screenshot?

**Comment by Moostek** [comment]
I have my version 2.606 and I can see there, exactly as shown on the setting picture. I can send you my .apk file. It is just there.

**Comment by papjul** [comment]
Send a screenshot in English instead

**Comment by papjul** [comment]
Nevermind, I found the relevant part of code: the Notification color setting is hidden on Android > 9.
https://github.com/WangDaYeeeeee/GeometricWeather/blob/2.608/app/src/main/java/wangdaye/com/geometricweather/settings/fragment/SettingsFragment.java#L366L373

This was completely removed on all Android versions when Geometric Weather moved to newer Settings design.

I guess it's a feature that was removed because it is no longer supported from Android 10, as you can see from this check here:
https://github.com/WangDaYeeeeee/GeometricWeather/blob/2.608/app/src/main/java/wangdaye/com/geometricweather/remoteviews/presenter/notification/NormalNotificationIMP.java#L269

So, I won't bring back a feature from a no longer supported version of Android.
