### ISSUE TITLE
Threshold for swiping through cities is quite too high

### ISSUE THREAD

**Issue by shaft17** [breezy-weather/breezy-weather#810]
### Steps to reproduce

I have more cities in my list of forecasts. When I'm on the main screen, it is possible to swipe between the cities.
In Geometric Weather 3.013 (the last version I have used) the swipe threshold for changing screen to the next/former city was around 10-20% swiping distance.
Now in Breezy it is around 50%, which I find quite high for flicking to the next screen.

### Expected behavior

I'd like to have either an option to set the swipe threshold (maybe there are other people who like it as is), but in general one should not swipe over half of the screen to come to the next city.
It should be in "thumb reach", i.e. 10-20% of the screen width.

### Actual behavior

As written above. Threshold is around 50% of the screen, which is quite high.

### Weather source used

AccuWeather

### Breezy Weather version

5.1.3.beta standard

### Android version

Android 11

### Device

Pixel 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.1.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
I understand that this might feel like a big jump from the too sensitive Geometric Weather swipe distance to the new distance in Breezy Weather.

However, this is the default swipe distance of the `ViewPager2`. I checked many other apps before reverting to this distance. They ALL had a 50% distance (I'm sure you can find an exception but that's not the point).

This is a normal behavior, and you need a few days to get used to it. I remember I also felt like you the first few days ;)

**Comment by shaft17** [comment]
I'm not fond of "you have to get used to it", because no launcher I've ever discovered has a 50% threshold for swiping sideways.
I do understand, but yeah, controversial.
Thanks anyway.

**Comment by shaft17** [comment]
I don't want to nag, but I dove deeper into the ViewPager2.

Did you consider the swiping speed in calculation?
Take Play Store as an example, the cards or widgets in the bottom row have indeed a 50% threshold - UNLESS you are swiping faster, then the threshold reduces.
I'm not sure if Google uses ViewPager2, but I assume they do.

Maybe we have a misunderstanding here, but it isn't intuitive for fast swiping that one should have cross more than half of the screen page.

I ask you to try it by yourself in Play Store. Thanks mate.

**Comment by papjul** [comment]
I'm using LineageOS default launcher, it has about 40% threshold. I don't have Google Play Store.

But you can’t compare with the experience of a launcher, because:
1) in a launcher, you have the same background everywhere, while in Breezy Weather, it depends on the weather condition of the location and it has to load the whole location + refresh it if necessary, so you can’t have a transition as smooth.
2) we have horizontal swipes in many cards. We had way too many users unintentionally swiping to the next city instead of the cards. Even then, we decided not to remove the ability to swipe between locations (although it's not a good thing to have two horizontal swipe events), and let it be but with a 50% swipe distance so that it has to be intentional.

As explained, the transition is not smooth, so we really don't want user to mistakenly switch to the next location and have loading times twice (once and then to go back).

Initially, I wanted to remove that swipe between locations to not have two horizontal swipe events, but users wanted to keep it.

> it isn't intuitive for fast swiping

As explained, we don't want fast swiping.

> Did you consider the swiping speed in calculation?

I can review a pull request that takes into account this parameter.

**Comment by shaft17** [comment]
> As explained, the transition is not smooth, so we really don't want user to mistakenly switch to the next location and have loading times twice (once and then to go back).

I get it and can agree with you.
Thanks for taking the time to reply!
