### ISSUE TITLE
[Icon packs] Add support for weather icons in XML/SVG format

### ISSUE THREAD

**Issue by oldherl** [breezy-weather/breezy-weather#857]
### Describe your idea

I've found a set of FOSS weather icons at https://basmilius.github.io/weather-icons/index.html
It's in animated SVG format. If breezy-weather could support this format, it would be easier to build an icon pack and save space too.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to a question covered in the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document, or a feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 5.1.7 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
The animations we support for icons is not continuous, it’s only for 1 or 2 seconds when you tap on the icon, so you will probably need to rewrite the animation for it to fit with the kind of animation we have, so that we don't animate it for 2 seconds, then abruptly stop the animation.
Please check this document written by Geometric Weather developer if you want to know more about it:
https://github.com/breezy-weather/breezy-weather-icon-packs/blob/main/INSTRUCTIONS.md

I can keep the issue to add support for regular SVG through XML files (I think that's the way Android supports them) so that you would only have to write the animation.

In the meantime, you can convert your SVG to PNG and they will be animated with the standard animation style. Running `oxipng` with the highest settings can greatly reduce filesizes of PNG icons so that the difference between XML vs PNG becomes only minor.
