### ISSUE TITLE
[June 2024] Removal notice - OpenWeatherMap source

### ISSUE THREAD

**Issue by papjul** [breezy-weather/breezy-weather#934]
### Discussed in https://github.com/breezy-weather/breezy-weather/discussions/933

<div type='discussions-op-text'>

<sup>Originally posted by **cloneofghosts** April 12, 2024</sup>
I'd create an issue for this but I wasn't sure which issue template to use as none of them really match.

OpenWeatherMap is deprecating Version 2.5 of their One Call API in favor of Version 3.0. Visiting https://openweathermap.org/api/one-call-api shows this message:

> One Call API 2.5 will be deprecated in June 2024. Please read the [detailed guide](https://openweathermap.org/one-call-transfer) for transitioning to the more advanced [One Call API 3.0](https://openweathermap.org/api/one-call-3) which includes several useful upgrades like 40+ years of history archive, daily aggregation and human readable daily summary in comparison with One Call API 2.5 version. Read more about One Call API 3.0 in the product documentation [page](https://openweathermap.org/api/one-call-3) and [FAQ](https://openweathermap.org/faq#onecall).

You haven't been able to make a API key for One Call 2.5 for a while now since when you try to signup you are doing so for Version 3.0. Looks like the only way to use their One Call API is to enable billing on your account.</div>

**Comment by cloneofghosts** [comment]
I think it's just One Call Version 2.5 is being deprecated and according to the [pricing page](https://openweathermap.org/price) you should still be able to access these APIs without billing:

- [Current Weather](https://openweathermap.org/current)
- [3-hour Forecast 5 days](https://openweathermap.org/forecast5)
- [Air Pollution API](https://openweathermap.org/api/air-pollution)
- [Geocoding API](https://openweathermap.org/api/geocoding-api)

I haven't seen anything which states that these APIs will also be deprecated but it wouldn't surprise me if they did depreciate them at some point in order to push everyone into using One Call 3.0.

The current weather API has no UV index and there was a UV Index API but it's been depreciated and you can only get UV Index data in their One Call API. There current conditions API also offers no alerts.

**Comment by papjul** [comment]
Thank you for your investigation!

At the moment, we only use the air pollution API which could technically still be used. Other endpoints would have to be implemented. However, I don't think anyone is willing to spend time re-implementing this source, because as you said it yourself:

> it wouldn't surprise me if they did depreciate them at some point in order to push everyone into using One Call 3.0

Additionally, it's a source that is often rate-limited, requiring an API key, so I believe most people are turning to the many other sources that don't have such requirements.

**Comment by papjul** [comment]
bb324b359efb1c0e0a4e438203bd0c79e2f5417f brings back air quality secondary source.

Do current weather and 3-hour Forecast 5 days require different API keys?

(Btw, we don't use their geocoding API as it doesn't have the mandatory timezone field)

**Comment by papjul** [comment]
Alright, 3-hourly forecast is implemented: 27d4c9dec58e5a54f566a90b5469581b0e28c3bb
