### ISSUE TITLE
"Send Gadgetbridge Data" disables itself intermittently

### ISSUE THREAD

**Issue by Allastratou** [breezy-weather/breezy-weather#956]
### Steps to reproduce

1. Enable "Send Gadgetbridge Data"
2. Wait 1-4 weeks
3. Watch stops receiving weather data through gadgetbridge 
4. Check setting in Breezy Weather, it's disabled
5. Start from "1."

### Expected behavior

Setting should stay enabled.

### Actual behavior

After 1-4 weeks, setting disables itself. All other settings remain normal

### Weather source used

accuweather

### Breezy Weather version

5.2.0 fdroid

### Android version

Android 13

### Device

Google Pixel 4a 5g

### Other details

This has been happening for about 3 months at least? I thought it was Google disabling "unaccessed" apps over time, so I disabled that feature. Also disabled any sort of battery optimizations and all that. All permissions are still enabled, all other settings remain unaffected, at least seemingly.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I read the [Frequently Asked Questions](https://github.com/breezy-weather/breezy-weather/blob/main/HELP.md) document and followed instructions if relevant.
- [X] I have updated the app to **[version 5.2.0 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.
- [X] I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance), unless my issue only happens with a specific language
- [X] I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.

**Comment by papjul** [comment]
Due to privacy concerns, we had to disable it twice.

The first time, when we found out that all apps coild intercept private data to ensure all users were aware of the risks: https://developer.android.com/privacy-and-security/risks/implicit-intent-hijacking?hl=en

The second time is now. We removed sending to all apps, and we let you decide which apps you want to send to. Once again, we decided to turn off all apps so you could which apps you want to allow.

Now, the feature is stable and it is very unlikely it will happen again.

Breaking changes like that are always mentioned in the changelog: https://github.com/breezy-weather/breezy-weather/blob/main/CHANGELOG.md

**Comment by Allastratou** [comment]
That's great to hear. My apologies for not having done my due diligence in checking the change logs.
